--Purpose    : For Version Manager
--Created On : NA
--Created By : NA
--Impact     : NA

CREATE TABLE APPLIED_PATCHES (
  PATCH_NAME VARCHAR2(1000 BYTE) NOT NULL, 
  UPDATE_TIMESTAMP DATE DEFAULT SYSDATE, 
  CONSTRAINT APPLIED_PATCHES_PK PRIMARY KEY (PATCH_NAME) ENABLE
) 
/
COMMIT
/
