--PURPOSE    : PATCH TO ADD DOCUMENT.
--AUTHOR     : Meghana Ganapaiah
--CREATED ON : 23RD September 2013

CREATE TABLE DOCUMENT
  (
    ID           NUMBER(19,0) NOT NULL ENABLE,
    CONTENT_TYPE VARCHAR2(255 CHAR),
    DESCRIPTION  VARCHAR2(255 CHAR),
    FILE_NAME    VARCHAR2(255 CHAR),
    FILE_SIZE    NUMBER(10,0),
    UPLOADED_ON  NUMBER(19,0),
    VERSION      NUMBER(10,0) NOT NULL ENABLE,
    UPLOADED_BY  NUMBER(19,0),
    D_CREATED_ON DATE,
    D_INTERNAL_COMMENTS VARCHAR2(255 CHAR),
    D_UPDATED_ON DATE,
    D_LAST_UPDATED_BY NUMBER(19,0),
    D_CREATED_TIME TIMESTAMP (6),
    D_UPDATED_TIME TIMESTAMP (6),
    DOCUMENT_TYPE           VARCHAR2(255 CHAR),
    D_ACTIVE                NUMBER(1,0) DEFAULT 1,
    IS_ELIGIBILITY_TO_SHARE NUMBER(1,0),
    MANDATORY               NUMBER(1,0),
    R3_DOC_ID               NUMBER,
    ORPHAN                  NUMBER(1,0) DEFAULT 1,
    CONTENT BLOB,
    ATTACHMENT_TYPE         NUMBER(19,0),
    IS_SHARED_WITH_SUPPLIER NUMBER(1,0),
    IS_SHARED_WITH_DEALER   NUMBER(1,0),
    CONSTRAINT DOCUMENT_PK PRIMARY KEY (ID) ENABLE
  )
/  
CREATE INDEX DOCUMENT_UPLOADEDBY_IX ON DOCUMENT
      (
        UPLOADED_BY
      )
/
CREATE INDEX DOCUMENT_R3_DOC_TMP_INDX ON DOCUMENT
    (
      R3_DOC_ID
    )
/