 --PURPOSE    : PATCH TO ADD NEW TABLES AND INDEXES.
--AUTHOR     : Meghana Ganapaiah
--CREATED ON : 23RD September 2013 
ALTER TABLE NOTIFICATION_MESSAGE_PARAMETER add CONSTRAINT FK_NOTIFICATION_MESSAGE FOREIGN KEY (NOTIFICATION_MESSAGE) REFERENCES ABSTRACT_NOTIFICATION_MESSAGE (ID) ENABLE
/