--PURPOSE    : PATCH TO CREATE TRAVEL_MATRIX_APPL_CONTRACTS TABLE
--AUTHOR     : PAYAL MOONDRA
--CREATED ON : 18-SEP-2013

CREATE TABLE TRAVEL_MATRIX_APPL_CONTRACTS
  (
    FLEET_CONTRACT         NUMBER(19,0),
    FOR_APPL_TRAVEL_MATRIX NUMBER(19,0)
  )
/