--PURPOSE    : PATCH TO ADD SYNONYM for permission
--AUTHOR     : SUSHMA MANTHALE
--CREATED ON : 30-sep-2013
CREATE OR REPLACE SYNONYM MST_ADMIN_FNC_AREA FOR NACCO_UAT_TESTING.MST_ADMIN_FNC_AREA
/
CREATE OR REPLACE SYNONYM MST_ADMIN_SUBJECT_AREA FOR NACCO_UAT_TESTING.MST_ADMIN_SUBJECT_AREA
/
CREATE OR REPLACE SYNONYM SUBJECT_FUNC_AREA_MAPPING FOR NACCO_UAT_TESTING.SUBJECT_FUNC_AREA_MAPPING
/
CREATE OR REPLACE SYNONYM MST_ADMIN_ACTION FOR NACCO_UAT_TESTING.MST_ADMIN_ACTION
/
CREATE OR REPLACE SYNONYM ROLE_PERMISSION_MAPPING FOR NACCO_UAT_TESTING.ROLE_PERMISSION_MAPPING
/
CREATE OR REPLACE SYNONYM MST_ADMIN_FNC_AREA_SEQ FOR NACCO_UAT_TESTING.MST_ADMIN_FNC_AREA_SEQ
/
CREATE OR REPLACE SYNONYM MST_ADMIN_SUBJECT_AREA_SEQ FOR NACCO_UAT_TESTING.MST_ADMIN_SUBJECT_AREA_SEQ
/
CREATE OR REPLACE SYNONYM ROLE_PERMISSION_MAPPING_SEQ FOR NACCO_UAT_TESTING.ROLE_PERMISSION_MAPPING_SEQ
/
CREATE OR REPLACE SYNONYM ROLE_PERMISSION_MAPPING_SEQ FOR NACCO_UAT_TESTING.ROLE_PERMISSION_MAPPING_SEQ
/
CREATE OR REPLACE SYNONYM ROLE_SEQ FOR NACCO_UAT_TESTING.ROLE_SEQ
/
