--PURPOSE    : PATCH TO CREATE PMT_EXPT_FOR_TRAVEL_RATES TABLE
--AUTHOR     : PAYAL MOONDRA
--CREATED ON : 18-SEP-2013


ALTER TABLE PMT_EXPT_FOR_TRAVEL_RATES ADD CONSTRAINT PYMT_EXCPTN_FOR_TRAVEL_FK FOREIGN KEY (FOR_PYMT_EXCPTN) REFERENCES PAYMENT_EXCEPTIONS (ID)
/
ALTER TABLE PMT_EXPT_FOR_TRAVEL_RATES ADD CONSTRAINT TRAVEL_RATES_FK FOREIGN KEY (FOR_TRAVEL_RATES) REFERENCES TRAVEL_RATE_EXCEPTIONS (ID)
/