 --PURPOSE    : PATCH TO ADD DOCUMENT.
--AUTHOR     : Meghana Ganapaiah
--CREATED ON : 23RD September 2013
ALTER TABLE DOCUMENT add CONSTRAINT DOCUMENT_LST_UPDT_BY_FK FOREIGN KEY (D_LAST_UPDATED_BY) REFERENCES ORG_USER (ID) ENABLE
/
ALTER TABLE DOCUMENT add CONSTRAINT DOCUMENT_UPLOADEDBY_FK FOREIGN KEY (UPLOADED_BY) REFERENCES ORG_USER (ID) ENABLE
/
ALTER TABLE DOCUMENT add CONSTRAINT ATTACHMENT_TYPE_FK FOREIGN KEY (ATTACHMENT_TYPE) REFERENCES LIST_OF_VALUES (ID) ENABLE
/