--PURPOSE    : PATCH TO ADD NEW TABLES AND INDEXES.
--AUTHOR     : Meghana Ganapaiah
--CREATED ON : 23RD September 2013

CREATE TABLE USER_ATTR_VALUE
  (
    ID NUMBER(19,0) NOT NULL ENABLE,
    CONSTRAINT USER_ATTR_VALUE_PK PRIMARY KEY (ID) ENABLE    
  )
/