--Purpose    : Patch for creating foriegn keys for FLEET_CONTRACT_ATTACHMENTS table
--Author     : Suneetha Nagaboyina
--Created On : 23-SEP-2013
ALTER TABLE FLEET_CONTRACT_ATTACHMENTS add CONSTRAINT FK_FLEET_CRT_ATTACH FOREIGN KEY (FLEET_CONTRACT) REFERENCES CONTRACT (ID) ENABLE
/
ALTER TABLE FLEET_CONTRACT_ATTACHMENTS add CONSTRAINT FK_ATTACHMENT_FLEET_CRT FOREIGN KEY (ATTACHMENTS) REFERENCES DOCUMENT (ID) ENABLE
/