--PURPOSE    : PATCH TO ADD TABLE TECHNICIAN_DETAIL
--AUTHOR     : SUSHMA MANTHALE
--CREATED ON : 16-JULY-13

CREATE TABLE  TECHNICIAN_DETAIL
  (
    ID                           NUMBER(19,0),
    VERSION                      NUMBER(10,0),
    DATE_OF_ARRIVAL              DATE,
    DATE_OF_COMPLETION           DATE,
    ESTIMATED_TIME_OF_ARRIVAL    VARCHAR2(255 CHAR),
    ESTIMATED_TIME_OF_COMPLETION VARCHAR2(255 CHAR),
    TECHNICIAN                   NUMBER(19,0),
    CONSTRAINT TECHNICIAN_DETAIL_ID_PK PRIMARY KEY (ID) ENABLE,
    CONSTRAINT TECHDETAIL_TECHNICIAN_FK FOREIGN KEY (TECHNICIAN) REFERENCES ORG_USER (ID) ENABLE
  )
/
CREATE SEQUENCE TECHNICIAN_DETAIL_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 20 START WITH 100000000000400 CACHE 20 NOORDER NOCYCLE
/