--Purpose    : Patch for creating CONFIG_PARAM tables
--Author     : Meghana Ganapaiah
--Created On : 23-SEP-2013
CREATE TABLE CONFIG_PARAM
  (
    ID           NUMBER(19,0) NOT NULL ,
    DESCRIPTION  VARCHAR2(255 CHAR) NOT NULL ,
    DISPLAY_NAME VARCHAR2(255 CHAR) NOT NULL ,
    NAME         VARCHAR2(255 CHAR) NOT NULL ,
    TYPE         VARCHAR2(255 CHAR) NOT NULL ,
    D_CREATED_ON DATE,
    D_INTERNAL_COMMENTS VARCHAR2(255 CHAR),
    D_UPDATED_ON DATE,
    D_LAST_UPDATED_BY NUMBER(19,0),
    D_CREATED_TIME TIMESTAMP (6),
    D_UPDATED_TIME TIMESTAMP (6),
    D_ACTIVE            NUMBER(1,0) DEFAULT 1,
    PARAM_DISPLAY_TYPE  VARCHAR2(50 BYTE),
    LOGICAL_GROUP       VARCHAR2(20 BYTE),
    LOGICAL_GROUP_ORDER NUMBER(20,0),
    SECTIONS            VARCHAR2(50 BYTE),
    SECTIONS_ORDER      NUMBER(20,0),
    PARAM_ORDER         NUMBER(20,0),
    CONSTRAINT "CONFIG_PARAM_PK" PRIMARY KEY ("ID")   
  )
/
CREATE SEQUENCE CONFIG_PARAM_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 20 START WITH 110000000012060 CACHE 20 NOORDER NOCYCLE
/