--PURPOSE    : PATCH TO ADD TABLE SERVICE_REQUEST
--AUTHOR     : SUSHMA MANTHALE
--CREATED ON : 16-JULY-13

CREATE TABLE SERVICE_REQUEST
  (
    ID                         NUMBER(19,0) NOT NULL ENABLE,
    VERSION                    NUMBER(10,0) NOT NULL ENABLE,
    FOR_ITEM                   NUMBER(19,0),
    SERVICE_REQUEST_NUMBER     VARCHAR2(255 CHAR),
    CUSTOMER_LOCATION          NUMBER(19,0),
    FOR_DEALER                 NUMBER(19,0),
    FILED_BY                   NUMBER(19,0),
    FAULT_CODE_REF             NUMBER(19,0),
    D_CREATED_ON               DATE,
    D_INTERNAL_COMMENTS        VARCHAR2(255 CHAR),
    D_UPDATED_ON                DATE,
    D_LAST_UPDATED_BY            NUMBER(19,0),
    D_CREATED_TIME               TIMESTAMP (6),
    D_UPDATED_TIME               TIMESTAMP (6),
    D_ACTIVE                     NUMBER(1,0) DEFAULT 1,
    BUSINESS_UNIT_INFO           VARCHAR2(255 CHAR),
    DEALER_TYPE                  VARCHAR2(255 CHAR),
    ACTIVE_SERVICE_REQUEST_AUDIT NUMBER(19,0),
    UPDATED                      NUMBER(1,0),
    QUOTE_DETAIL                 NUMBER(19,0),
    NOTIFICATION_STATUS          VARCHAR2(255 CHAR),
    CONSTRAINT SR_ID_PK PRIMARY KEY (ID) ENABLE
  )
/
CREATE SEQUENCE SERVICE_REQUEST_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 20 START WITH 100000000015600 CACHE 20 NOORDER NOCYCLE
/