--PURPOSE    : PATCH TO ADD NEW TABLES AND INDEXES.
--AUTHOR     : Meghana Ganapaiah
--CREATED ON : 23RD September 2013

ALTER TABLE ATTR_VALUE add CONSTRAINT ATTRVALUE_ATTRIBUTE_FK FOREIGN KEY (ATTRIBUTE) REFERENCES ATTRIBUTE (ID) ENABLE
/
ALTER TABLE ATTR_VALUE add CONSTRAINT ATTR_VALUE_LST_UPDT_BY_FK FOREIGN KEY (D_LAST_UPDATED_BY) REFERENCES ORG_USER (ID) ENABLE
/