--PURPOSE    : PATCH TO CREATE MISC_PMT_EXCPTNS TABLE
--AUTHOR     : PAYAL MOONDRA
--CREATED ON : 18-SEP-2013

CREATE TABLE MISC_PMT_EXCPTNS
  (
    FOR_PYMT_EXCPTN   NUMBER(19,0),
    FOR_MISCELLANEOUS NUMBER(19,0)
  )
/