--Purpose    : Patch for creating CONFIG_PARAM tables
--Author     : Meghana Ganapaiah
--Created On : 23-SEP-2013
ALTER TABLE CONFIG_VALUE add CONSTRAINT CONFIG_VALUE_BU_FK FOREIGN KEY (BUSINESS_UNIT_INFO) REFERENCES BUSINESS_UNIT (NAME) ENABLE
/
ALTER TABLE CONFIG_VALUE add CONSTRAINT CONFIG_VALUE_LST_UPDT_BY_FK FOREIGN KEY (D_LAST_UPDATED_BY) REFERENCES ORG_USER (ID) ENABLE
/