--PURPOSE    : PATCH TO CREATE CUSTOMER_LOCATION_CONTACTS TABLE
--AUTHOR     : PAYAL MOONDRA
--CREATED ON : 18-SEP-2013




ALTER TABLE CUSTOMER_LOCATION_CONTACTS ADD CONSTRAINT CLC_CUSTOMER_LOCATION_FK FOREIGN KEY(CUSTOMER_LOCATION) REFERENCES CUSTOMER_LOCATIONS(ID)
/
ALTER TABLE CUSTOMER_LOCATION_CONTACTS ADD CONSTRAINT CLC_CONTACTS_FK FOREIGN KEY (CONTACT) REFERENCES CUSTOMER_CONTACT (ID)
/