--PURPOSE    : PATCH TO ADD NEW TABLES AND INDEXES.
--AUTHOR     : Meghana Ganapaiah
--CREATED ON : 18th September 2013
CREATE TABLE ABSTRACT_NOTIFICATION_MESSAGE
(
    ID               NUMBER,
    MESSAGE_TEMPLATE VARCHAR2(255 BYTE),
    NUMBER_OF_TRIALS NUMBER,
    CREATION_DATE DATE,
    MESSAGE_STATE VARCHAR2(255 BYTE),
    PARAM_MAP CLOB,
    RECIPIENT VARCHAR2(255 BYTE),
    VERSION   NUMBER,
    TYPE      VARCHAR2(255 BYTE),
    EXCEPTION VARCHAR2(255 BYTE),
    PRIMARY KEY (ID) 
)
/