--Purpose    : CREATING_TABLE_CONTACT_EVENT_STATES
--Author     : VAMSI KRISHNA JOLLA
--Created On : 18-SEP-2013

CREATE TABLE CONTACT_EVENT_STATES
  (
    EVENT_STATE 	NUMBER(19,0) NOT NULL ENABLE,
    CONTACT     	NUMBER(19,0) NOT NULL ENABLE,
    CONSTRAINT CLC_EVENT_STATE_FK FOREIGN KEY (EVENT_STATE) REFERENCES EVENT_STATE (ID) ENABLE,
    CONSTRAINT CLC_CONTACT_FK FOREIGN KEY (CONTACT) REFERENCES CUSTOMER_CONTACT (ID) ENABLE
  )
/