--PURPOSE    : PATCH TO ALTER CUSTOMER_LOCATIONS TABLE
--AUTHOR     : PAYAL MOONDRA


ALTER table CUSTOMER_LOCATIONS ADD CONSTRAINT CUSTOMERLOCATIONS_CUSTOMER_FK FOREIGN KEY (CUSTOMER) REFERENCES FLEET_CUSTOMER(ID) ENABLE
/
ALTER table CUSTOMER_LOCATIONS ADD CONSTRAINT CUSTOMER_LOCATIONS_ID_FK FOREIGN KEY (ID) REFERENCES ORGANIZATION (ID) ENABLE
/