--PURPOSE    : PATCH TO ALTER CUSTOMER_CONTACT TABLE
--AUTHOR     : PAYAL MOONDRA
--CREATED ON : 25-SEP-2013


ALTER TABLE CUSTOMER_CONTACT modify PHONE VARCHAR2(255 CHAR)
/
ALTER TABLE CUSTOMER_CONTACT modify FAX VARCHAR2(255 CHAR)
/
ALTER TABLE CUSTOMER_CONTACT ADD PHONE_EXTENSION VARCHAR2(255 CHAR)
/
ALTER TABLE CUSTOMER_CONTACT ADD FAX_EXTENSION VARCHAR2(255 CHAR)
/