--PURPOSE    : PATCH TO CREATE LABOR_RATE_EXCEPTIONS TABLE
--AUTHOR     : PAYAL MOONDRA
--CREATED ON : 18-SEP-2013
ALTER TABLE LABOR_RATE_EXCEPTIONS ADD constraint LABOR_RATE_DEALER_FK FOREIGN KEY (DEALER) REFERENCES SERVICE_PROVIDER (ID)
/