  --PURPOSE    : PATCH TO ADD NEW TABLES AND INDEXES.
--AUTHOR     : Meghana Ganapaiah
--CREATED ON : 23RD September 2013
ALTER TABLE NOTIFICATION_PARAMETER add CONSTRAINT FK_NOTIFICATION_EVENT FOREIGN KEY (NOTIFICATION_EVENT) REFERENCES NOTIFICATION_EVENT (ID) ENABLE
/