--PURPOSE    : PATCH TO CREATE CUSTOMER_LOCATIONS TABLE
--AUTHOR     : PAYAL MOONDRA

CREATE TABLE CUSTOMER_LOCATIONS
(
    CUSTOMER                     NUMBER(19,0) NOT NULL ENABLE,
    LOCATIONS_MAPKEY             VARCHAR2(255 CHAR),
    ID                           NUMBER(19,0) NOT NULL ENABLE,
    QUOTE_THRESHOLD_AMT          NUMBER(19,2),
    QUOTE_THRESHOLD_CURR         VARCHAR2(255 CHAR),
    DEALER_QUOTE_VARIANCE        NUMBER(19,2),
    VARIANCE_IN_PERCENTAGE       NUMBER(1,0),
    CREATE_SERVICE_REQUEST       NUMBER(1,0),
    PERIODIC_SERVICE_CALL        NUMBER(1,0),
    ETA_ON_SERVICE_REQUEST       NUMBER(1,0),
    SELF_DIAGONOSIS_ENABLED      NUMBER(1,0),
    UPDATE_OPEN_SERVICE_REQUEST  NUMBER(1,0),
    SELF_DIAGNOSIS_MANDATORY     NUMBER(1,0),
    PURCHASE_ORDER_REQUIRED      NUMBER(1,0),
    DUPLICATE_PO_NUMBER_ALLOWED  NUMBER(1,0),
    PO_LENGTH_SPECIFIED          NUMBER(1,0),
    PURCHASE_ORDER_LENGTH        NUMBER(2,0),
    PO_REGULAR_EXPRESSION        VARCHAR2(255 CHAR),
    PO_DETAILS                   VARCHAR2(255 CHAR),
    CUSTOMER_NOTES               VARCHAR2(255 CHAR),
    IS_ACTIVE                    NUMBER(1,0),
    CODE                         VARCHAR2(255 CHAR),
    SPECIAL_INSTRUCTIONS         VARCHAR2(255 CHAR),
    CONSTRAINT CUSTOMER_LOCATIONS_PK PRIMARY KEY (ID) ENABLE
   
  )
/
CREATE SEQUENCE CUSTOMER_LOCATIONS_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 20 START WITH 100000000000000 CACHE 20 NOORDER NOCYCLE
/