--PURPOSE    : PATCH TO ADD TABLE JBPM_PROCESSDEFINITION 
--AUTHOR     : SUSHMA MANTHALE
--CREATED ON : 16-JULY-13


CREATE TABLE JBPM_PROCESSDEFINITION
(	
ID_                        NUMBER(19,0) NOT NULL ENABLE, 
NAME_                      VARCHAR2(255 CHAR), 
VERSION_                   NUMBER(10,0), 
ISTERMINATIONIMPLICIT_     NUMBER(1,0), 
STARTSTATE_                NUMBER(19,0), 
CONSTRAINT JBPM_PROCESSDEFINITION_PK PRIMARY KEY (ID_) 
)
/