--Purpose    : Patch for creating foreign keys for CONTRACT_FOR_APPL_MACHINE table
--Author     : Suneetha Nagaboyina
--Created On : 23-SEP-2013


ALTER TABLE CONTRACT_FOR_APPL_MACHINE add CONSTRAINT FK_FLEET_CONT FOREIGN KEY (FLEET_CONTRACT) REFERENCES CONTRACT (ID) ENABLE
/
ALTER TABLE CONTRACT_FOR_APPL_MACHINE add CONSTRAINT FK_FLEET_APP_MCHS FOREIGN KEY (FOR_APPLICABLE_MACHINES) REFERENCES FLEET_INVENTORY_ITEM (ID) ENABLE
/