--Purpose    : Patch for creating foreign key for CUSTOMER_CONTACTS table
--Author     : Suneetha Nagaboyina
--Created On : 23-SEP-2013

ALTER TABLE CUSTOMER_CONTACTS add CONSTRAINT CUSTOMER_CONTACTS_FK FOREIGN KEY (CONTACT) REFERENCES CUSTOMER_CONTACT (ID) ENABLE
/
ALTER TABLE CUSTOMER_CONTACTS add CONSTRAINT CUSTOMER_FK FOREIGN KEY (CUSTOMER) REFERENCES FLEET_CUSTOMER (ID) ENABLE
/