 --PURPOSE    : PATCH TO CREATE TABLE FOR LOV.
--AUTHOR     : Meghana Ganapaiah
--CREATED ON : 23th September 2013
ALTER TABLE LIST_OF_VALUES add CONSTRAINT LIST_OF_VALUES_BU_FK FOREIGN KEY (BUSINESS_UNIT_INFO) REFERENCES BUSINESS_UNIT (NAME) ENABLE
/