--PURPOSE    : PATCH TO CREATE INSTALLED_PARTS TABLE
--AUTHOR     : RAVIKUMAR Y
--CREATED ON : 04-OCT-13

CREATE TABLE INSTALLED_PARTS
  (
    ID                           NUMBER(19,0),
    PART_NUMBER                  VARCHAR2(255 BYTE),
    EXTENDED_PRICE_PER_UNIT_AMT  NUMBER(19,2),
    EXTENDED_PRICE_PER_UNIT_CURR VARCHAR2(255 CHAR),
    NUMBER_OF_UNITS              NUMBER(10,0),
    PRICE_PER_UNIT_AMT           NUMBER(19,2),
    PRICE_PER_UNIT_CURR          VARCHAR2(255 CHAR),
    DESCRIPTION                  VARCHAR2(255 BYTE),
    PRICE                        NUMBER(19,0),
    ITEM                         NUMBER(19,0),
    D_CREATED_ON DATE,
    D_INTERNAL_COMMENTS VARCHAR2(255 CHAR),
    D_UPDATED_ON DATE,
    D_LAST_UPDATED_BY NUMBER(19,0),
    D_CREATED_TIME TIMESTAMP (6),
    D_ACTIVE NUMBER(1,0),
    D_UPDATED_TIME TIMESTAMP (6),
    SERIAL_NUMBER VARCHAR2(255 BYTE),
    INVOICE       NUMBER(19,0),
    CONSTRAINT INSTALLED_PARTS_PK PRIMARY KEY (ID) ENABLE
  )
/