--PURPOSE    : PATCH TO CREATE PMT_EXPT_FOR_TRAVEL_RATES TABLE
--AUTHOR     : PAYAL MOONDRA
--CREATED ON : 18-SEP-2013

CREATE TABLE PMT_EXPT_FOR_TRAVEL_RATES
  (
    FOR_PYMT_EXCPTN  NUMBER(19,0),
    FOR_TRAVEL_RATES NUMBER(19,0)
  )
/