--PURPOSE    : PATCH TO ADD TABLE JBPM_FORM_NODES
--AUTHOR     : SUSHMA MANTHALE
--CREATED ON : 16-JULY-13

ALTER TABLE JBPM_FORM_NODES ADD CONSTRAINT JBPM_FORM_NODES_PK PRIMARY KEY (FORM_TASK_NODE_FORM_ID, FORM_TYPE) ENABLE
/
ALTER TABLE JBPM_FORM_NODES ADD CONSTRAINT JBPMFORMNODES_FRMTSKNDFRMID_FK FOREIGN KEY (FORM_TASK_NODE_FORM_ID) REFERENCES JBPM_NODE (ID_) ENABLE
/
ALTER TABLE REPEATABLE_TRANSITION ADD CONSTRAINT REPEATABLETRANSIT_FORKNODE_FK FOREIGN KEY (FORK_NODE) REFERENCES JBPM_NODE (ID_) DISABLE
/