--PURPOSE    : PATCH TO CREATE TRAVEL_MATRIX TABLE
--AUTHOR     : PAYAL MOONDRA
--CREATED ON : 18-SEP-2013


ALTER TABLE TRAVEL_MATRIX ADD CONSTRAINT TRAVEL_MATRIX_DEALER_FK FOREIGN KEY (DEALER) REFERENCES SERVICE_PROVIDER (ID)
/