--Purpose    : Patch for altering SYNC_TRACKER table
--Author     : Suneetha Nagaboyina
--Created On : 04-OCT-2013
ALTER TABLE SYNC_TRACKER ADD CONSTRAINT SYNCTRACKER_STATUS_FK FOREIGN KEY (STATUS) REFERENCES SYNC_STATUS (STATUS) ENABLE
/
ALTER TABLE SYNC_TRACKER ADD CONSTRAINT SYNC_TRACKER_BU_FK FOREIGN KEY (BUSINESS_UNIT_INFO) REFERENCES BUSINESS_UNIT (NAME) ENABLE
/
ALTER TABLE SYNC_TRACKER ADD CONSTRAINT SYNC_TRACKER_LST_UPDT_BY_FK FOREIGN KEY (D_LAST_UPDATED_BY) REFERENCES ORG_USER (ID) ENABLE
/