--PURPOSE    : PATCH TO CREATE PMT_OVRDS_FOR_LABOR TABLE
--AUTHOR     : PAYAL MOONDRA
--CREATED ON : 18-SEP-2013

ALTER TABLE PMT_OVRDS_FOR_LABOR ADD CONSTRAINT PYMT_OVRDS_FOR_LABOR_FK FOREIGN KEY (FOR_PYMT_OVERRIDES) REFERENCES PAYMENT_OVERRIDES (ID)
/
ALTER TABLE PMT_OVRDS_FOR_LABOR ADD CONSTRAINT LABOR_PYMT_FK FOREIGN KEY (FOR_LABOR_PYMT) REFERENCES LABOR_PAYMENT_EXCEPTIONS (ID)
/