--PURPOSE    : PATCH TO ADD TABLE PMT_EXPT_FOR_NON_OEM_PRT
--AUTHOR     : SUSHMA MANTHALE
--CREATED ON : 16-JULY-13

CREATE TABLE  PMT_EXPT_FOR_NON_OEM_PRT
  (
    FOR_PYMT_EXCPTN  NUMBER(19,0),
    FOR_NON_OEMPARTS NUMBER(19,0),
    CONSTRAINT PYMT_EXCPTN_FOR_NON_OEM_FK FOREIGN KEY (FOR_PYMT_EXCPTN) REFERENCES PAYMENT_EXCEPTIONS (ID) ENABLE,
    CONSTRAINT NON_OEM_PARTS_FK FOREIGN KEY (FOR_NON_OEMPARTS) REFERENCES NON_OEM_PART_EXCEPTIONS (ID) ENABLE
  )
/