--PURPOSE    : PATCH TO ADD TABLE Fleet inventory item
--AUTHOR     : SUSHMA MANTHALE
--CREATED ON : 04-JULY-13


CREATE TABLE FLEET_INVENTORY_ITEM
  (
    ID                        NUMBER(19,0),
    VERSION                   NUMBER(10,0),
    CUSTOMER                  NUMBER(19,0),
    MAINTENANCE_TYPE          VARCHAR2(255 CHAR),
    EXTERNAL_ID               VARCHAR2(255 CHAR),
    CONTRACT_CODE             VARCHAR2(255 CHAR),
    UNIT_PO_NUMBER            VARCHAR2(255 CHAR),
    UNIT_SALES_ORDER_NUMBER   VARCHAR2(255 CHAR),
    STD_WARRANTY_EXPIRATION   DATE,
    EXT_WARRANTY_EXPIRATION   DATE,
    INVENTORY_ITEM            NUMBER(19,0),
    D_CREATED_ON              DATE,
    D_INTERNAL_COMMENTS       VARCHAR2(255 CHAR),
    D_UPDATED_ON              DATE,
    D_LAST_UPDATED_BY         NUMBER(19,0),
    D_CREATED_TIME            TIMESTAMP (6),
    D_UPDATED_TIME            TIMESTAMP (6),
    D_ACTIVE                  NUMBER(1,0) DEFAULT 1,
    BUSINESS_UNIT_INFO        VARCHAR2(255 CHAR),
    ASSET_NUMBER              VARCHAR2(255 CHAR),
    LAST_SERVICE_DATE         DATE,
    LEASE_START_DATE          DATE,
    LEASE_END_DATE            DATE,
    LEASE_ID                  VARCHAR2(255 CHAR),
    PREFERRED_DEALER          NUMBER(19,0),
    ALTERNATE_DEALER          NUMBER(19,0),
    UNIT_AGE                  NUMBER(19,0),
    EQUIPMENT_CONDITION       VARCHAR2(255 CHAR),
    CONSTRAINT  FLEETINVENTORY_ID_PK PRIMARY KEY (ID) ENABLE

  )
/
CREATE SEQUENCE FLEET_INVENTORY_ITEM_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 20 START WITH 100000000000000 CACHE 20 NOORDER NOCYCLE
/