--PURPOSE    : PATCH TO ADD TABLE JBPM_RUNTIMEACTION
--AUTHOR     : SUSHMA MANTHALE
--CREATED ON : 16-JULY-13


 CREATE TABLE JBPM_RUNTIMEACTION 
   (	ID_                      NUMBER(19,0) NOT NULL ENABLE, 
	VERSION_                 NUMBER(10,0) NOT NULL ENABLE, 
	EVENTTYPE_               VARCHAR2(255 CHAR), 
	TYPE_                    CHAR(1 CHAR), 
	GRAPHELEMENT_            NUMBER(19,0), 
	PROCESSINSTANCE_         NUMBER(19,0), 
	ACTION_                  NUMBER(19,0), 
	PROCESSINSTANCEINDEX_    NUMBER(10,0),
 
	CONSTRAINT JBPM_RUNTIMEACTION_PK PRIMARY KEY (ID_) ENABLE
)
/