--PURPOSE    : PATCH TO CREATE TRAVEL_MATRIX_APPL_CONTRACTS TABLE
--AUTHOR     : PAYAL MOONDRA
--CREATED ON : 18-SEP-2013


ALTER TABLE TRAVEL_MATRIX_APPL_CONTRACTS ADD CONSTRAINT CONTRACT_FK FOREIGN KEY (FLEET_CONTRACT) REFERENCES CONTRACT (ID) ENABLE
/
ALTER TABLE TRAVEL_MATRIX_APPL_CONTRACTS ADD CONSTRAINT FK_FLEET_APP_TRAVEL_MATRIX FOREIGN KEY (FOR_APPL_TRAVEL_MATRIX) REFERENCES TRAVEL_MATRIX (ID)
/