--PURPOSE    : PATCH TO ADD TABLE COST_CATEGORY
--AUTHOR     : SUSHMA MANTHALE
--CREATED ON : 05-JULY-13


CREATE TABLE COST_CATEGORY
  (
    ID                   NUMBER(19,0) NOT NULL ENABLE,
    CODE                 VARCHAR2(255 CHAR),
    DESCRIPTION          VARCHAR2(255 CHAR),
    NAME                 VARCHAR2(255 CHAR),
    VERSION              NUMBER(10,0) NOT NULL ENABLE,
    D_CREATED_ON         DATE,
    D_CREATED_TIME       TIMESTAMP (6),
    D_INTERNAL_COMMENTS  VARCHAR2(255 CHAR),
    D_UPDATED_ON         DATE,
    D_UPDATED_TIME       TIMESTAMP (6),
    D_LAST_UPDATED_BY    NUMBER(19,0),
    D_ACTIVE             NUMBER(1,0) DEFAULT 1,
    CONSTRAINT COST_CATEGORY_PK PRIMARY KEY (ID) ENABLE
  )
/
CREATE SEQUENCE COST_CATEGORY_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 20 START WITH 110000000000840 CACHE 20 NOORDER NOCYCLE
/