--Purpose    : Patch for ADMIN SERVICE_CODES SETUP TABLES
--Author     : MOHAN DOLA
--Created On : 18-SEP-2013
CREATE TABLE MANAGE_SERVICE_CODES
(
ID                  NUMBER(19,0) NOT NULL ENABLE,
SERVICE_CODE         VARCHAR2(255 CHAR),
SERVICE_DESCRIPTION  VARCHAR2(255 CHAR),
COMMENTS            VARCHAR2(4000 CHAR),
BUSINESS_UNIT_INFO  VARCHAR2(255 CHAR),
D_CREATED_ON        DATE,
D_INTERNAL_COMMENTS VARCHAR2(255 CHAR),
D_UPDATED_ON        DATE,
D_LAST_UPDATED_BY   NUMBER(19,0),
D_CREATED_TIME      TIMESTAMP,
D_UPDATED_TIME      TIMESTAMP,
D_ACTIVE            NUMBER(1,0) DEFAULT 1,
VERSION             NUMBER(10,0) NOT NULL ENABLE,
STATUS              VARCHAR2(255 BYTE),
CATEGORY            VARCHAR2(255 CHAR),
CONSTRAINT MG_SERVICECODE_PK PRIMARY KEY (ID) ENABLE,
CONSTRAINT MG_SC_BU_FK FOREIGN KEY (BUSINESS_UNIT_INFO) REFERENCES BUSINESS_UNIT (NAME) ENABLE
)
/
CREATE TABLE SERVICE_CODE_INTERVAL
(
ID                   NUMBER(19,0) NOT NULL ENABLE,
FREQUENCY_HRS  NUMBER(19,0),
FREQUENCY_DAYS NUMBER(19,0),
MANAGE_SERVICE_CODE NUMBER(19,0),
ITEM_GROUP            VARCHAR2(255 CHAR),
D_CREATED_ON         DATE,
D_INTERNAL_COMMENTS  VARCHAR2(255 CHAR),
D_UPDATED_ON         DATE,
D_LAST_UPDATED_BY    NUMBER(19,0),
D_CREATED_TIME       TIMESTAMP,
D_UPDATED_TIME       TIMESTAMP,
D_ACTIVE             NUMBER(1,0) DEFAULT 1,
VERSION              NUMBER(10,0) NOT NULL ENABLE,
BUSINESS_UNIT_INFO   VARCHAR2(255 BYTE),
CONSTRAINT MG_SERVICECODEINTID_PK PRIMARY KEY (ID),
CONSTRAINT MG_SERVICECODEINT_FK FOREIGN KEY (MANAGE_SERVICE_CODE) REFERENCES MANAGE_SERVICE_CODES (ID)
)
/
CREATE TABLE SERVICE_CODE_FEE
(
ID                   NUMBER(19,0) NOT NULL ENABLE,
ACTIVE_FROM          NUMBER(19,0),
ACTIVE_TILL          NUMBER(19,0),
MANAGE_SERVICE_CODE NUMBER(19,0),
D_CREATED_ON         DATE,
D_INTERNAL_COMMENTS  VARCHAR2(255 CHAR),
D_UPDATED_ON         DATE,
D_LAST_UPDATED_BY    NUMBER(19,0),
D_CREATED_TIME       TIMESTAMP,
D_UPDATED_TIME       TIMESTAMP,
D_ACTIVE             NUMBER(1,0) DEFAULT 1,
VERSION              NUMBER(10,0) NOT NULL ENABLE,
BUSINESS_UNIT_INFO   VARCHAR2(255 BYTE),
CONSTRAINT MG_SERVICECODEFEE_PK PRIMARY KEY (ID),
CONSTRAINT MG_SERVICECODEFEE_FK FOREIGN KEY (MANAGE_SERVICE_CODE) REFERENCES MANAGE_SERVICE_CODES (ID)
)
/
CREATE TABLE MANAGE_SERVICE_CODE_AUDIT
(
ID                   NUMBER(19,0) NOT NULL ENABLE,
COMMENTS             VARCHAR2(4000 CHAR),
MANAGE_SERVICE_CODE NUMBER(19,0),
D_CREATED_ON         DATE,
D_INTERNAL_COMMENTS  VARCHAR2(255 CHAR),
D_UPDATED_ON         DATE,
D_LAST_UPDATED_BY    NUMBER(19,0),
D_CREATED_TIME       TIMESTAMP,
D_UPDATED_TIME       TIMESTAMP,
D_ACTIVE             NUMBER(1,0) DEFAULT 1,
VERSION              NUMBER(10,0) NOT NULL ENABLE,
BUSINESS_UNIT_INFO   VARCHAR2(255 BYTE),
CONSTRAINT MG_SERVICECODEAUDIT_PK PRIMARY KEY (ID),
CONSTRAINT MG_SERVICECODEIAUDIT_FK FOREIGN KEY (MANAGE_SERVICE_CODE) REFERENCES MANAGE_SERVICE_CODES (ID)
)
/
CREATE TABLE INCLUSIVE_SERVICE_CODES
(
ID  NUMBER(19,0) NOT NULL ENABLE,
PARENT_CODE NUMBER(19),
CHILD_CODE NUMBER(19),
CONSTRAINT IN_SERVICECODE_PK PRIMARY KEY (ID) ENABLE,
CONSTRAINT IN_PRT_SERVICECODE_FK FOREIGN KEY (PARENT_CODE) REFERENCES MANAGE_SERVICE_CODES (ID) ENABLE,
CONSTRAINT IN_CHD_SERVICECODE_FK FOREIGN KEY (CHILD_CODE) REFERENCES MANAGE_SERVICE_CODES (ID) ENABLE
)
/
CREATE SEQUENCE  INCLUSIVE_SERVICE_CODES_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 20 START WITH 100000000000100 CACHE 20 NOORDER  NOCYCLE
/
CREATE SEQUENCE  MANAGE_SERVICE_CODES_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 20 START WITH 100000000000100 CACHE 20 NOORDER  NOCYCLE
/
CREATE SEQUENCE  SERVICE_CODE_INTERVAL_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 20 START WITH 100000000000100 CACHE 20 NOORDER  NOCYCLE
/
CREATE SEQUENCE  SERVICE_CODE_FEE_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 20 START WITH 100000000000100 CACHE 20 NOORDER  NOCYCLE
/
CREATE SEQUENCE  MANAGE_SERVICE_CODE_AUDIT_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 20 START WITH 100000000000100 CACHE 20 NOORDER  NOCYCLE
/