--Purpose    : Patch for creating CONTRACT table
--Author     : Suneetha Nagaboyina
--Created On : 23-SEP-2013

CREATE TABLE CONTRACT
  (
    ID NUMBER(19,0) NOT NULL ENABLE,
    ACTIVE_FROM DATE,
    ACTIVE_TILL DATE,
    VERSION          NUMBER(10,0) NOT NULL ENABLE,
    CODE             VARCHAR2(255 CHAR),
    DESCRIPTION      VARCHAR2(255 CHAR),
    COMMENTS         VARCHAR2(4000 CHAR),
    TYPE             VARCHAR2(255 BYTE),
    FOR_CUSTOMER     NUMBER(19,0),
    SHIP_TO          NUMBER(19,0),
    CURRENTLY_ACTIVE NUMBER(1,0),
    D_CREATED_ON DATE,
    D_INTERNAL_COMMENTS VARCHAR2(255 CHAR),
    D_UPDATED_ON DATE,
    D_LAST_UPDATED_BY NUMBER(19,0),
    D_CREATED_TIME TIMESTAMP (6),
    D_UPDATED_TIME TIMESTAMP (6),
    D_ACTIVE                      NUMBER(1,0) DEFAULT 1,
    BUSINESS_UNIT_INFO            VARCHAR2(255 CHAR),
    STATUS                        VARCHAR2(255 BYTE),
    ALERT_WINDOW_FROM_EXPIRY_DATE NUMBER(19,0),
    REPORTING_CURRENCY            NUMBER(19,0),
    IS_TAX_ENABLED                NUMBER(1,0),
    INVOICING_INTERVAL            NUMBER(19,0),
    INVOICING_CURRENCY            NUMBER(19,0),
    BILL_TO_SITE_NUMBER           NUMBER(19,0),
    APPL_DLR_PYMT_EXCPTNS         NUMBER(19,0),
    APPL_DLR_PYMT_OVERRIDES       NUMBER(19,0),
    CONSTRAINT FLEET_CONTRACT_PK PRIMARY KEY (ID) ENABLE
  )
/

CREATE SEQUENCE FLEET_CONTRACT_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 20 START WITH 100000000000400 CACHE 20 NOORDER NOCYCLE
/