 --Purpose    : Patch for creating LABOR_PAYMENT_EXCEPTIONS
--Author     : Meghana Ganapaiah
--Created On : 18-SEP-2013

ALTER TABLE LABOR_PAYMENT_EXCEPTIONS add CONSTRAINT LABOR_PYMT_DLR_FK FOREIGN KEY (DEALER) REFERENCES SERVICE_PROVIDER (ID) ENABLE
/