--PURPOSE    : PATCH TO ADD TABLE PMT_EXPT_FOR_DRAYAGE
--AUTHOR     : SUSHMA MANTHALE
--CREATED ON : 16-JULY-13
alter table PMT_EXPT_FOR_DRAYAGE add CONSTRAINT PYMT_EXCPTN_FOR_DRAYAGE_FK FOREIGN KEY (FOR_PYMT_EXCPTN) REFERENCES PAYMENT_EXCEPTIONS (ID) ENABLE
/
alter table PMT_EXPT_FOR_DRAYAGE add CONSTRAINT DRAYAGE_FK FOREIGN KEY (FOR_DRAYAGE) REFERENCES DRAYAGE_EXCEPTIONS (ID) ENABLE
/