--Purpose    : CREATING_TABLE_SALES_RANGE
--Author     : VAMSI KRISHNA JOLLA
--Created On : 18-SEP-2013

CREATE TABLE SALES_RANGE
  (
    SALESMAN_ID   	NUMBER(5,0),
    SALESMAN_NAME 	VARCHAR2(30 BYTE),
    SALES_AMOUNT  	NUMBER(10,0),
    SALES_DATE 		DATE
  )
/