ALTER TABLE PMT_EXPT_FOR_LABOR_RATES add CONSTRAINT PYMT_EXCPTN_FOR_LABOR_FK FOREIGN KEY (FOR_PYMT_EXCPTN) REFERENCES PAYMENT_EXCEPTIONS (ID) ENABLE
/
ALTER TABLE PMT_EXPT_FOR_LABOR_RATES add CONSTRAINT LABOR_RATES_FK FOREIGN KEY (FOR_LABOR_RATES) REFERENCES LABOR_RATE_EXCEPTIONS (ID) ENABLE
/