--PURPOSE    : PATCH TO CREATE CUSTOMER_LOCATION_CONTACTS TABLE
--AUTHOR     : PAYAL MOONDRA
--CREATED ON : 18-SEP-2013



CREATE TABLE CUSTOMER_LOCATION_CONTACTS
  (
    CUSTOMER_LOCATION  NUMBER(19,0) NOT NULL ENABLE,
    CONTACT            NUMBER(19,0) NOT NULL ENABLE
  )
/