--PURPOSE    : PATCH FOR CREATING TABLE SERVICE_REQUEST_AUDIT
--AUTHOR     : VAMSI KRISHNA JOLLA
--CREATED ON : 18-Sep-2013
CREATE TABLE SERVICE_REQUEST_AUDIT
  (
    ID                         NUMBER(19,0) NOT NULL ENABLE,
    VERSION                    NUMBER(10,0) NOT NULL ENABLE,
    UPDATED_ON                 NUMBER(19,0),
    UPDATED_BY                 NUMBER(19,0),
    UPDATED_TIME               TIMESTAMP (6),
    FOR_SERVICE_REQUEST        NUMBER(19,0),
    STATE                      VARCHAR2(255 CHAR),
    CREATED_ON                 NUMBER(19,0),
    CREATED_BY                 NUMBER(19,0),
    CREATED_TIME               TIMESTAMP (6),
    CUSTOMER_PO_NUMBER         VARCHAR2(255 CHAR),
    EQUIPMENT_DOWN             VARCHAR2(20 BYTE),
    EMERGENCY_REQUEST          VARCHAR2(20 BYTE),
    QUOTE_REQUIRED             VARCHAR2(20 BYTE),
    SELF_DIAGNOSED             VARCHAR2(20 BYTE),
    FAULT_CODE                 VARCHAR2(40 CHAR),
    CALL_TYPE                  VARCHAR2(255 BYTE),
    PROBLEM_DESCRIPTION        VARCHAR2(4000 BYTE),
    POSSIBLE_FAULT_LOCATION    VARCHAR2(255 BYTE),
    ADDITIONAL_DETAILS         VARCHAR2(4000 BYTE),
    COMMENTS                   VARCHAR2(4000 BYTE),
    RENTAL_START_DATE          DATE,
    RENTAL_END_DATE            DATE,
    TECHNICIAN_DETAILS         NUMBER(19,0),
    ATTACHMENTS                NUMBER(19,0),
    LIST_INDEX                 NUMBER(10,0),
    D_CREATED_ON               DATE,
    D_INTERNAL_COMMENTS        VARCHAR2(255 CHAR),
    D_UPDATED_ON                DATE,
    D_LAST_UPDATED_BY            NUMBER(19,0),
    D_CREATED_TIME               TIMESTAMP (6),
    D_UPDATED_TIME               TIMESTAMP (6),
    D_ACTIVE                     NUMBER(1,0) DEFAULT 1,
    EXTERNAL_COMMENTS          VARCHAR2(4000 BYTE),
    CONSTRAINT SR_PK PRIMARY KEY (ID) ENABLE
  )
/
CREATE SEQUENCE SERVICE_REQUEST_AUDIT_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 20 START WITH 8801 CACHE 20 NOORDER NOCYCLE
/
CREATE TABLE SERVICE_REQUEST_AUDIT_ATTMNTS
  (
    SERVICE_REQUEST_AUDIT NUMBER(19,0) NOT NULL ENABLE,
    ATTACHMENTS           NUMBER(19,0) NOT NULL ENABLE,
    CONSTRAINT SRAA_ATTACHMENTS_FK FOREIGN KEY (ATTACHMENTS) REFERENCES DOCUMENT (ID) ENABLE,
    CONSTRAINT SRAA_SERVICEREQUESTAUDIT_FK FOREIGN KEY (SERVICE_REQUEST_AUDIT) REFERENCES SERVICE_REQUEST_AUDIT (ID) ENABLE
  )
/