--Purpose    : Patch for creating foriegn keys for CONTRACT_FOR_DEALER_GROUPS table
--Author     : Suneetha Nagaboyina
--Created On : 23-SEP-2013


ALTER TABLE CONTRACT_FOR_DEALER_GROUPS add CONSTRAINT FK_FLEET_CT_ FOREIGN KEY (FLEET_CONTRACT) REFERENCES CONTRACT (ID) ENABLE
/
ALTER TABLE CONTRACT_FOR_DEALER_GROUPS add CONSTRAINT FK_FLEET_DEAR_GROUPS FOREIGN KEY (FOR_DEALER_GROUPS) REFERENCES DEALER_GROUP (ID) ENABLE
/