--PURPOSE    : PATCH TO ADD TABLE JBPM_PROCESSINSTANCE
--AUTHOR     : SUSHMA MANTHALE
--CREATED ON : 16-JULY-13


  CREATE TABLE JBPM_PROCESSINSTANCE
   (	ID_                    NUMBER(19,0) NOT NULL ENABLE, 
	VERSION_               NUMBER(10,0) NOT NULL ENABLE, 
	START_                 TIMESTAMP (6), 
	END_                   TIMESTAMP (6), 
	ISSUSPENDED_           NUMBER(1,0), 
	PROCESSDEFINITION_     NUMBER(19,0), 
	ROOTTOKEN_             NUMBER(19,0), 
	SUPERPROCESSTOKEN_     NUMBER(19,0), 
	CONSTRAINT JBPM_PROCESSINSTANCE_PK PRIMARY KEY (ID_) ENABLE
   )
/