--PURPOSE    : PATCH TO ADD NEW TABLES AND INDEXES.
--AUTHOR     : Meghana Ganapaiah
--CREATED ON : 18th September 2013

CREATE TABLE NOTIFICATION_EVENT
  (
    ID               NUMBER,
    EVENT_NAME       VARCHAR2(255 BYTE),
    ENTITY_NAME      VARCHAR2(255 BYTE),
    NUMBER_OF_TRIALS NUMBER,
    PENDING          NUMBER(1,0),
    D_CREATED_ON DATE,
    D_CREATED_TIME TIMESTAMP (6),
    D_INTERNAL_COMMENTS VARCHAR2(255 CHAR),
    D_UPDATED_ON DATE,
    D_UPDATED_TIME TIMESTAMP (6),
    D_LAST_UPDATED_BY NUMBER(19,0),
    D_ACTIVE          NUMBER(1,0),
    PRIMARY KEY (ID)
    )
/