--Purpose    : Patch for creating foreign keys for CONTRACT_FOR_SERVICE_PROVIDERS table
--Author     : Suneetha Nagaboyina
--Created On : 23-SEP-2013

ALTER TABLE CONTRACT_FOR_SERVICE_PROVIDERS add CONSTRAINT FK_FLEET_CONTRACT FOREIGN KEY (FLEET_CONTRACT) REFERENCES CONTRACT (ID) ENABLE
/
ALTER TABLE CONTRACT_FOR_SERVICE_PROVIDERS add CONSTRAINT FK_FLEET_SERV_PVDR FOREIGN KEY (FOR_SERVICE_PROVIDERS) REFERENCES SERVICE_PROVIDER (ID) ENABLE
/