--PURPOSE    : PATCH FOR CREATING TABLE SERVICE_REQUEST_AUDIT
--AUTHOR     : VAMSI KRISHNA JOLLA
--CREATED ON : 18-Sep-2013

 ALTER TABLE SERVICE_REQUEST_AUDIT ADD CONSTRAINT SRA_TECHNICIAN_DETAILS_FK5 FOREIGN KEY (TECHNICIAN_DETAILS) REFERENCES TECHNICIAN_DETAIL (ID) ENABLE
/
ALTER TABLE SERVICE_REQUEST_AUDIT ADD CONSTRAINT SRA_FOR_SR_FK1 FOREIGN KEY (FOR_SERVICE_REQUEST) REFERENCES SERVICE_REQUEST (ID) ENABLE
/