--PURPOSE    : PATCH TO Alter TABLE SERVICE_REQUEST
--AUTHOR     : SUSHMA MANTHALE
--CREATED ON : 16-JULY-13

ALTER table SERVICE_REQUEST ADD CONSTRAINT SR_FLEETINVENTORY_FK FOREIGN KEY (FOR_ITEM) REFERENCES FLEET_INVENTORY_ITEM (ID) ENABLE
/
ALTER table SERVICE_REQUEST ADD CONSTRAINT SR_FAULT_CODE_REF_FK FOREIGN KEY (FAULT_CODE_REF) REFERENCES FAULT_CODE (ID) ENABLE
/
ALTER table SERVICE_REQUEST ADD CONSTRAINT SR_BUSINESS_UNIT_INFO_FK FOREIGN KEY (BUSINESS_UNIT_INFO) REFERENCES BUSINESS_UNIT (NAME) ENABLE
/
ALTER table SERVICE_REQUEST ADD CONSTRAINT SR_CUSTOMER_LOCATIONS_FK FOREIGN KEY (CUSTOMER_LOCATION) REFERENCES CUSTOMER_LOCATIONS (ID) ENABLE
/
ALTER table SERVICE_REQUEST ADD CONSTRAINT SR_ACTSREQAUDT_FK FOREIGN KEY (ACTIVE_SERVICE_REQUEST_AUDIT) REFERENCES SERVICE_REQUEST_AUDIT (ID) ENABLE
/
ALTER table SERVICE_REQUEST ADD CONSTRAINT SR_FOR_DEALER_FK FOREIGN KEY (FOR_DEALER) REFERENCES SERVICE_PROVIDER (ID) ENABLE
/
ALTER table SERVICE_REQUEST ADD CONSTRAINT SR_FILED_BY_FK FOREIGN KEY (FILED_BY) REFERENCES ORG_USER (ID) ENABLE
/