--PURPOSE    : PATCH TO ADD NEW TABLES AND INDEXES.
--AUTHOR     : Meghana Ganapaiah
--CREATED ON : 23RD September 2013

CREATE TABLE ATTRIBUTE
  (
    ID      NUMBER(19,0) NOT NULL ENABLE,
    NAME    VARCHAR2(255 CHAR),
    VERSION NUMBER(10,0) NOT NULL ENABLE,
    D_CREATED_ON DATE,
    D_INTERNAL_COMMENTS VARCHAR2(255 CHAR),
    D_UPDATED_ON DATE,
    D_LAST_UPDATED_BY NUMBER(19,0),
    D_CREATED_TIME TIMESTAMP (6),
    D_UPDATED_TIME TIMESTAMP (6),
    D_ACTIVE           NUMBER(1,0) DEFAULT 1,
    BUSINESS_UNIT_INFO VARCHAR2(255 CHAR),
    CONSTRAINT ATTRIBUTE_PK PRIMARY KEY (ID) ENABLE
  )
/
CREATE INDEX ATTRIBUTE_I1 ON ATTRIBUTE
    (
      NAME
    )
/