--PURPOSE    : PATCH TO CREATE TABLE REPEATABLE_TRANSITION
--AUTHOR     : RAVIKUMAR Y
--CREATED ON : 22-JULY-13

CREATE TABLE REPEATABLE_TRANSITION
(
    FORK_NODE                 NUMBER(19,0) NOT NULL ENABLE,
    TRANSITION_NAME           VARCHAR2(255 CHAR),
    REPETITION_CRITERIA_CLASS VARCHAR2(255 CHAR),
    INPUT_EXPRESSION          VARCHAR2(255 CHAR),
    OUTPUT_EXPRESSION         VARCHAR2(255 CHAR),
    LIST_INDEX                NUMBER(10,0) NOT NULL ENABLE,
    CONSTRAINT REPEATABLE_TRANSITION_PK PRIMARY KEY (FORK_NODE, LIST_INDEX) ENABLE
)
/
CREATE TABLE JBPM_ACTION
  (
    ID_                    NUMBER(19,0) NOT NULL ENABLE,
    CLASS                  CHAR(1 CHAR) NOT NULL ENABLE,
    NAME_                  VARCHAR2(255 CHAR),
    ISPROPAGATIONALLOWED_   NUMBER(1,0),
    ACTIONEXPRESSION_       VARCHAR2(255 CHAR),
    ISASYNC_                NUMBER(1,0),
    REFERENCEDACTION_       NUMBER(19,0),
    ACTIONDELEGATION_       NUMBER(19,0),
    EVENT_                  NUMBER(19,0),
    PROCESSDEFINITION_      NUMBER(19,0),
    TIMERNAME_              VARCHAR2(255 CHAR),
    EXPRESSION_             VARCHAR2(4000 CHAR),
    DUEDATE_                VARCHAR2(255 CHAR),
    REPEAT_                 VARCHAR2(255 CHAR),
    TRANSITIONNAME_         VARCHAR2(255 CHAR),
    TIMERACTION_            NUMBER(19,0),
    EVENTINDEX_             NUMBER(10,0),
    EXCEPTIONHANDLER_       NUMBER(19,0),
    EXCEPTIONHANDLERINDEX_  NUMBER(10,0),
    CONSTRAINT JBPM_ACTION_PK PRIMARY KEY (ID_) ENABLE
  )
/
CREATE TABLE JBPM_BYTEARRAY
  (
    ID_               NUMBER(19,0) NOT NULL ENABLE,
    NAME_             VARCHAR2(255 CHAR),
    FILEDEFINITION_   NUMBER(19,0),
    CONSTRAINT JBPM_BYTEARRAY_PK PRIMARY KEY (ID_) ENABLE
  )
/
CREATE TABLE JBPM_BYTEBLOCK
  (
    PROCESSFILE_   NUMBER(19,0) NOT NULL ENABLE,
    BYTES_         RAW(1024),
    INDEX_         NUMBER(10,0) NOT NULL ENABLE,
    CONSTRAINT  JBPM_BYTEBLOCK_PK PRIMARY KEY (PROCESSFILE_, INDEX_) ENABLE
  )
/
CREATE TABLE JBPM_COMMENT
  (
    ID_                  NUMBER(19,0) NOT NULL ENABLE,
    VERSION_             NUMBER(10,0) NOT NULL ENABLE,
    ACTORID_             VARCHAR2(255 CHAR),
    TIME_                TIMESTAMP (6),
    MESSAGE_             VARCHAR2(4000 CHAR),
    TOKEN_               NUMBER(19,0),
    TASKINSTANCE_        NUMBER(19,0),
    TOKENINDEX_          NUMBER(10,0),
    TASKINSTANCEINDEX_   NUMBER(10,0),
    CONSTRAINT JBPM_COMMENT_PK PRIMARY KEY (ID_) ENABLE
  )
/
CREATE TABLE JBPM_DECISIONCONDITIONS
  (
    DECISION_           NUMBER(19,0) NOT NULL ENABLE,
    TRANSITIONNAME_     VARCHAR2(255 CHAR),
    EXPRESSION_         VARCHAR2(255 CHAR),
    INDEX_              NUMBER(10,0) NOT NULL ENABLE,
    CONSTRAINT JBPM_DECISIONCONDITIONS_PK PRIMARY KEY (DECISION_, INDEX_) ENABLE
  )
/
CREATE TABLE JBPM_DELEGATION
  (
    ID_               NUMBER(19,0) NOT NULL ENABLE,
    CLASSNAME_         VARCHAR2(4000 CHAR),
    CONFIGURATION_     VARCHAR2(4000 CHAR),
    CONFIGTYPE_        VARCHAR2(255 CHAR),
    PROCESSDEFINITION_ NUMBER(19,0),
    CONSTRAINT JBPM_DELEGATION_PK PRIMARY KEY (ID_) ENABLE
  )
/
CREATE TABLE JBPM_EVENT
  (
    ID_                NUMBER(19,0) NOT NULL ENABLE,
    EVENTTYPE_         VARCHAR2(255 CHAR),
    TYPE_              CHAR(1 CHAR),
    GRAPHELEMENT_      NUMBER(19,0),
    TRANSITION_        NUMBER(19,0),
    TASK_              NUMBER(19,0),
    NODE_              NUMBER(19,0),
    PROCESSDEFINITION_ NUMBER(19,0),
    CONSTRAINT JBPM_EVENT_PK PRIMARY KEY (ID_) ENABLE
  )
/
CREATE TABLE JBPM_EXCEPTIONHANDLER
  (
    ID_                  NUMBER(19,0) NOT NULL ENABLE,
    EXCEPTIONCLASSNAME_  VARCHAR2(4000 CHAR),
    TYPE_                CHAR(1 CHAR),
    GRAPHELEMENT_        NUMBER(19,0),
    TRANSITION_          NUMBER(19,0),
    GRAPHELEMENTINDEX_   NUMBER(10,0),
    TASK_                NUMBER(19,0),
    NODE_                NUMBER(19,0),
    PROCESSDEFINITION_   NUMBER(19,0),
    CONSTRAINT JBPM_EXCEPTIONHANDLER_PK PRIMARY KEY (ID_) ENABLE
  )
/
CREATE TABLE JBPM_LOG
  (
    ID_               NUMBER(19,0) NOT NULL ENABLE,
    CLASS_            CHAR(1 CHAR) NOT NULL ENABLE,
    INDEX_            NUMBER(10,0),
    DATE_             TIMESTAMP (6),
    TOKEN_            NUMBER(19,0),
    PARENT_           NUMBER(19,0),
    CHILD_            NUMBER(19,0),
    SWIMLANEINSTANCE_ NUMBER(19,0),
    EXCEPTION_        VARCHAR2(4000 CHAR),
    ACTION_           NUMBER(19,0),
    VARIABLEINSTANCE_ NUMBER(19,0),
    MESSAGE_          VARCHAR2(4000 CHAR),
    TASKACTORID_      VARCHAR2(255 CHAR),
    TASKOLDACTORID_   VARCHAR2(255 CHAR),
    TRANSITION_       NUMBER(19,0),
    SOURCENODE_       NUMBER(19,0),
    DESTINATIONNODE_  NUMBER(19,0),
    NODE_             NUMBER(19,0),
    ENTER_            TIMESTAMP (6),
    LEAVE_            TIMESTAMP (6),
    DURATION_         NUMBER(19,0),
    NEWLONGVALUE_     NUMBER(19,0),
    OLDLONGVALUE_     NUMBER(19,0),
    OLDSTRINGIDCLASS_ VARCHAR2(255 CHAR),
    OLDSTRINGIDVALUE_ VARCHAR2(255 CHAR),
    NEWSTRINGIDCLASS_ VARCHAR2(255 CHAR),
    NEWSTRINGIDVALUE_ VARCHAR2(255 CHAR),
    OLDSTRINGVALUE_   VARCHAR2(4000 CHAR),
    NEWSTRINGVALUE_   VARCHAR2(4000 CHAR),
    OLDLONGIDCLASS_   VARCHAR2(255 CHAR),
    OLDLONGIDVALUE_   NUMBER(19,0),
    NEWLONGIDCLASS_   VARCHAR2(255 CHAR),
    NEWLONGIDVALUE_   NUMBER(19,0),
    OLDDOUBLEVALUE_   FLOAT(126),
    NEWDOUBLEVALUE_   FLOAT(126),
    OLDDATEVALUE_     TIMESTAMP (6),
    NEWDATEVALUE_     TIMESTAMP (6),
    OLDBYTEARRAY_     NUMBER(19,0),
    NEWBYTEARRAY_     NUMBER(19,0),
    TASKINSTANCE_     NUMBER(19,0),
    CONSTRAINT JBPM_LOG_PK PRIMARY KEY (ID_) ENABLE
  )
/
CREATE TABLE JBPM_MESSAGE
  (
    ID_             NUMBER(19,0) NOT NULL ENABLE,
    CLASS_          CHAR(1 CHAR) NOT NULL ENABLE,
    DESTINATION_    VARCHAR2(255 CHAR),
    EXCEPTION_      VARCHAR2(4000 CHAR),
    ISSUSPENDED_    NUMBER(1,0),
    TOKEN_          NUMBER(19,0),
    NODE_           NUMBER(19,0),
    TEXT_           VARCHAR2(255 CHAR),
    ACTION_         NUMBER(19,0),
    TRANSITIONNAME_ VARCHAR2(255 CHAR),
    TASKINSTANCE_   NUMBER(19,0),
    CONSTRAINT JBPM_MESSAGE_PK PRIMARY KEY (ID_) ENABLE
  )
/
CREATE TABLE JBPM_MODULEDEFINITION
  (
    ID_                NUMBER(19,0) NOT NULL ENABLE,
    CLASS_             CHAR(1 CHAR) NOT NULL ENABLE,
    NAME_              VARCHAR2(4000 CHAR),
    PROCESSDEFINITION_ NUMBER(19,0),
    STARTTASK_         NUMBER(19,0),
    CONSTRAINT JBPM_MODULEDEFINITION_PK PRIMARY KEY (ID_) ENABLE
  )
/
CREATE TABLE JBPM_MODULEINSTANCE
  (
    ID_                 NUMBER(19,0) NOT NULL ENABLE,
    CLASS_              CHAR(1 CHAR) NOT NULL ENABLE,
    PROCESSINSTANCE_    NUMBER(19,0),
    TASKMGMTDEFINITION_ NUMBER(19,0),
    NAME_               VARCHAR2(255 CHAR),
    CONSTRAINT JBPM_MODULEINSTANCE_PK PRIMARY KEY (ID_) ENABLE
  )
/
CREATE TABLE JBPM_NODE
  (
    ID_                   NUMBER(19,0) NOT NULL ENABLE,
    CLASS_                CHAR(1 CHAR) NOT NULL ENABLE,
    NAME_                 VARCHAR2(255 CHAR),
    PROCESSDEFINITION_    NUMBER(19,0),
    ISASYNC_              NUMBER(1,0),
    ACTION_               NUMBER(19,0),
    SUPERSTATE_           NUMBER(19,0),
    SIGNAL_               NUMBER(10,0),
    CREATETASKS_          NUMBER(1,0),
    ENDTASKS_             NUMBER(1,0),
    TASK_NAMES_TO_END     VARCHAR2(255 CHAR),
    DECISIONEXPRESSION_   VARCHAR2(255 CHAR),
    DECISIONDELEGATION    NUMBER(19,0),
    SUBPROCESSDEFINITION_ NUMBER(19,0),
    END_TRANSITION        VARCHAR2(255 CHAR),
    NORMAL_TRANSITION     VARCHAR2(255 CHAR),
    NODECOLLECTIONINDEX_  NUMBER(10,0),
    CONSTRAINT JBPM_NODE_PK PRIMARY KEY (ID_) ENABLE
  )
/
CREATE TABLE JBPM_SWIMLANE
   (	
        ID_                       NUMBER(19,0) NOT NULL ENABLE, 
	NAME_                     VARCHAR2(255 CHAR), 
	ACTORIDEXPRESSION_        VARCHAR2(255 CHAR), 
	POOLEDACTORSEXPRESSION_   VARCHAR2(255 CHAR), 
	ASSIGNMENTDELEGATION_     NUMBER(19,0), 
	TASKMGMTDEFINITION_       NUMBER(19,0),
 
	 CONSTRAINT JBPM_SWIMLANE_PK PRIMARY KEY (ID_) ENABLE
   )
/
CREATE TABLE JBPM_SWIMLANEINSTANCE
   (	ID_                 NUMBER(19,0) NOT NULL ENABLE, 
	NAME_               VARCHAR2(255 CHAR), 
	ACTORID_            VARCHAR2(255 CHAR), 
	SWIMLANE_           NUMBER(19,0), 
	TASKMGMTINSTANCE_   NUMBER(19,0), 

	CONSTRAINT JBPM_SWIMLANEINSTANCE_PK PRIMARY KEY (ID_) ENABLE
   )
/
CREATE TABLE JBPM_TASK
   (	ID_                       NUMBER(19,0) NOT NULL ENABLE, 
	NAME_                     VARCHAR2(255 CHAR), 
	PROCESSDEFINITION_        NUMBER(19,0), 
	DESCRIPTION_              VARCHAR2(4000 CHAR), 
	ISBLOCKING_               NUMBER(1,0), 
	ISSIGNALLING_             NUMBER(1,0), 
	DUEDATE_                  VARCHAR2(255 CHAR), 
	ACTORIDEXPRESSION_        VARCHAR2(255 CHAR), 
	POOLEDACTORSEXPRESSION_   VARCHAR2(255 CHAR), 
	TASKMGMTDEFINITION_       NUMBER(19,0), 
	TASKNODE_                 NUMBER(19,0), 
	STARTSTATE_               NUMBER(19,0), 
	ASSIGNMENTDELEGATION_     NUMBER(19,0), 
	SWIMLANE_                 NUMBER(19,0), 
	TASKCONTROLLER_           NUMBER(19,0), 
	CONSTRAINT JBPM_TASK_PK PRIMARY KEY (ID_) ENABLE
   )
/
CREATE TABLE JBPM_TASKACTORPOOL
   (	
   POOLEDACTOR_      NUMBER(19,0) NOT NULL ENABLE, 
	
   TASKINSTANCE_     NUMBER(19,0) NOT NULL ENABLE, 
	
   CONSTRAINT JBPM_TASKACTORPOOL_PK PRIMARY KEY (POOLEDACTOR_, TASKINSTANCE_)
)
/
CREATE TABLE JBPM_TASKCONTROLLER
   (	
        ID_                          NUMBER(19,0) NOT NULL ENABLE, 
	TASKCONTROLLERDELEGATION_    NUMBER(19,0), 
	 CONSTRAINT JBPM_TASKCONTROLLER_PK PRIMARY KEY (ID_) ENABLE
   )
/
CREATE TABLE JBPM_TASKINSTANCE
   (	ID_                      NUMBER(19,0) NOT NULL ENABLE, 
	CLASS_                   CHAR(1 CHAR) NOT NULL ENABLE, 
	NAME_                    VARCHAR2(255 CHAR), 
	DESCRIPTION_             VARCHAR2(4000 CHAR), 
	ACTORID_                 VARCHAR2(255 CHAR), 
	CREATE_                  TIMESTAMP (6), 
	START_                   TIMESTAMP (6), 
	END_                     TIMESTAMP (6), 
	DUEDATE_                 TIMESTAMP (6), 
	PRIORITY_                NUMBER(10,0), 
	ISCANCELLED_             NUMBER(1,0), 
	ISSUSPENDED_             NUMBER(1,0), 
	ISOPEN_                  NUMBER(1,0), 
	ISSIGNALLING_            NUMBER(1,0), 
	ISBLOCKING_              NUMBER(1,0), 
	TASK_                    NUMBER(19,0), 
	TOKEN_                   NUMBER(19,0), 
	SWIMLANINSTANCE_         NUMBER(19,0), 
	TASKMGMTINSTANCE_        NUMBER(19,0), 
	QUOTE_ID                 NUMBER(19,0),
        SERVICE_REQUEST_ID       NUMBER(19,0),
	 
	 CONSTRAINT JBPM_TASKINSTANCE_PK PRIMARY KEY (ID_)ENABLE
   )
/
CREATE TABLE JBPM_TIMER
   (	ID_                       NUMBER(19,0) NOT NULL ENABLE, 
	NAME_                     VARCHAR2(255 CHAR), 
	DUEDATE_                  TIMESTAMP (8), 
	REPEAT_                   VARCHAR2(255 CHAR), 
	TRANSITIONNAME_           VARCHAR2(255 CHAR), 
	EXCEPTION_                VARCHAR2(4000 CHAR), 
	ISSUSPENDED_              NUMBER(1,0), 
	ACTION_                   NUMBER(19,0), 
	TOKEN_                    NUMBER(19,0), 
	PROCESSINSTANCE_          NUMBER(19,0), 
	TASKINSTANCE_             NUMBER(19,0), 
	GRAPHELEMENTTYPE_         VARCHAR2(255 CHAR), 
	GRAPHELEMENT_             NUMBER(19,0), 

	CONSTRAINT JBPM_TIMER_PK PRIMARY KEY (ID_)ENABLE
   )
/
CREATE TABLE JBPM_TOKEN
   (	
        ID_                         NUMBER(19,0) NOT NULL ENABLE, 
	VERSION_                    NUMBER(10,0) NOT NULL ENABLE, 
	NAME_                       VARCHAR2(255 CHAR), 
	START_                      TIMESTAMP (6), 
	END_                        TIMESTAMP (6), 
	NODEENTER_                  TIMESTAMP (6), 
	NEXTLOGINDEX_               NUMBER(10,0), 
	ISABLETOREACTIVATEPARENT_   NUMBER(1,0), 
	ISTERMINATIONIMPLICIT_      NUMBER(1,0), 
	ISSUSPENDED_                NUMBER(1,0), 
	NODE_                       NUMBER(19,0), 
	PROCESSINSTANCE_            NUMBER(19,0), 
	PARENT_                     NUMBER(19,0), 
	SUBPROCESSINSTANCE_         NUMBER(19,0), 
	CONSTRAINT JBPM_TOKEN_PK PRIMARY KEY (ID_)
)
/
CREATE TABLE JBPM_TOKENVARIABLEMAP
   (	
        ID_                 NUMBER(19,0)NOT NULL ENABLE, 
	TOKEN_              NUMBER(19,0), 
	CONTEXTINSTANCE_    NUMBER(19,0), 
	CONSTRAINT JBPM_TOKENVARIABLEMAP_PK PRIMARY KEY (ID_)
)
/
CREATE TABLE JBPM_TRANSITION
  (
    ID_                NUMBER(19,0) NOT NULL ENABLE,
    NAME_              VARCHAR2(255 CHAR),
    PROCESSDEFINITION_ NUMBER(19,0),
    FROM_              NUMBER(19,0),
    TO_                NUMBER(19,0),
    FROMINDEX_         NUMBER(10,0),
    CONSTRAINT JBPM_TRANSITION_PK PRIMARY KEY (ID_) ENABLE
  )
/
CREATE TABLE JBPM_VARIABLEACCESS
  (
    ID_             NUMBER(19,0) NOT NULL ENABLE,
    VARIABLENAME_   VARCHAR2(255 CHAR),
    ACCESS_         VARCHAR2(255 CHAR),
    MAPPEDNAME_     VARCHAR2(255 CHAR),
    TASKCONTROLLER_ NUMBER(19,0),
    INDEX_          NUMBER(10,0),
    PROCESSSTATE_   NUMBER(19,0),
    SCRIPT_         NUMBER(19,0),
    CONSTRAINT JBPM_VARIABLEACCESS_PK PRIMARY KEY (ID_) ENABLE
  )
/
CREATE TABLE JBPM_VARIABLEINSTANCE
  (
    ID_               NUMBER(19,0) NOT NULL ENABLE,
    CLASS_            CHAR(1 CHAR) NOT NULL ENABLE,
    NAME_             VARCHAR2(255 CHAR),
    CONVERTER_        CHAR(1 CHAR),
    TOKEN_            NUMBER(19,0),
    TOKENVARIABLEMAP_ NUMBER(19,0),
    PROCESSINSTANCE_  NUMBER(19,0),
    BYTEARRAYVALUE_   NUMBER(19,0),
    LONGVALUE_        NUMBER(19,0),
    STRINGVALUE_      VARCHAR2(4000 CHAR),
    DOUBLEVALUE_      FLOAT(126),
    STRINGIDCLASS_    VARCHAR2(255 CHAR),
    LONGIDCLASS_      VARCHAR2(255 CHAR),
    DATEVALUE_        TIMESTAMP (6),
    TASKINSTANCE_     NUMBER(19,0),
    CONSTRAINT JBPM_VARIABLEINSTANCE_PK PRIMARY KEY (ID_) ENABLE
  )
/
CREATE TABLE JBPM_FORM_NODES
  (
    FORM_TASK_NODE_FORM_ID NUMBER(19,0) NOT NULL ENABLE,
    FORM_VALUE             VARCHAR2(255 CHAR),
    FORM_TYPE              VARCHAR2(255 CHAR) NOT NULL ENABLE
  )
/