--PURPOSE    : PATCH TO CREATE TABLE FOR LOV.
--AUTHOR     : Meghana Ganapaiah
--CREATED ON : 23th September 2013

CREATE TABLE LIST_OF_VALUES
(
    TYPE        VARCHAR2(50 BYTE),
    CODE        VARCHAR2(255 CHAR) NOT NULL ENABLE,
    DESCRIPTION VARCHAR2(255 CHAR),
    STATE       VARCHAR2(255 CHAR),
    VERSION     NUMBER(10,0) NOT NULL ENABLE,
    D_CREATED_ON DATE,
    D_INTERNAL_COMMENTS VARCHAR2(255 CHAR),
    D_UPDATED_ON DATE,
    D_LAST_UPDATED_BY  NUMBER(19,0),
    ID                 NUMBER(19,0),
    BUSINESS_UNIT_INFO VARCHAR2(255 CHAR),
    D_CREATED_TIME TIMESTAMP (6),
    D_UPDATED_TIME TIMESTAMP (6),
    D_ACTIVE NUMBER(1,0) DEFAULT 1,
    CONSTRAINT LIST_OF_VALUES_PK PRIMARY KEY (ID) 
)
/
CREATE INDEX LIST_OF_VALUES_IDX_CO ON LIST_OF_VALUES(CODE)
/