--Purpose    : Patch to alter TECHNICIAN_DETAIL table
--Author     : Priyanka Gautam
--Created On : 10-OCT-2013
ALTER TABLE TECHNICIAN_DETAIL
ADD(
TECHNICIAN_CERTIFIED VARCHAR2(20 BYTE),
ETA_IN_HOURS NUMBER(19,0),
ETA_IN_MINUTES NUMBER(19,0),
DEALER_COMMENTS VARCHAR2(4000 BYTE)
)
/