--PURPOSE    : PATCH TO ADD NEW TABLES AND INDEXES.
--AUTHOR     : Meghana Ganapaiah
--CREATED ON : 23RD September 2013

CREATE TABLE DEFAULT_FOLDER_VIEW
  (
    ID                 NUMBER(19,0) NOT NULL ENABLE,
    FOLDER_NAME        VARCHAR2(255 BYTE) NOT NULL ENABLE,
    DEFAULT_INBOX_VIEW NUMBER(19,0) NOT NULL ENABLE,
    CREATED_BY         NUMBER(19,0) NOT NULL ENABLE,
    CONSTRAINT DEFAULT_FOLDER_VIEW_PK PRIMARY KEY (ID) ENABLE  
  )
/
CREATE INDEX DEFAULTFOLDERVIEW_CREATEDBY_IX ON DEFAULT_FOLDER_VIEW
  (
    CREATED_BY
  )
/
CREATE INDEX DEFAULTFOLDERVIEW_INBOXVIEW_IX ON DEFAULT_FOLDER_VIEW
  (
    DEFAULT_INBOX_VIEW
  )
/