--PURPOSE    : PATCH TO ADD TABLE PMT_EXPT_FOR_DRAYAGE
--AUTHOR     : SUSHMA MANTHALE
--CREATED ON : 16-JULY-13

CREATE TABLE PMT_EXPT_FOR_DRAYAGE
  (
    FOR_PYMT_EXCPTN  NUMBER(19,0),
    FOR_DRAYAGE      NUMBER(19,0)
  )
/