--Purpose    : Patch for creating SYNC_TRACKER table
--Author     : Suneetha Nagaboyina
--Created On : 04-OCT-2013
CREATE TABLE SYNC_TRACKER
  (
    ID NUMBER(19,0) NOT NULL ENABLE,
    BODXML CLOB,
    BUSINESS_ID VARCHAR2(255 CHAR),
    CREATE_DATE TIMESTAMP (6),
    ERROR_MESSAGE CLOB,
    ERROR_TYPE     VARCHAR2(255 CHAR),
    NO_OF_ATTEMPTS NUMBER(10,0),
    RECORD CLOB,
    START_TIME TIMESTAMP (6),
    SYNC_TYPE       VARCHAR2(255 CHAR),
    UNIQUE_ID_NAME  VARCHAR2(255 CHAR),
    UNIQUE_ID_VALUE VARCHAR2(255 CHAR),
    UPDATE_DATE TIMESTAMP (6),
    VERSION NUMBER(10,0),
    STATUS  VARCHAR2(255 CHAR),
    D_CREATED_ON DATE,
    D_INTERNAL_COMMENTS VARCHAR2(255 CHAR),
    D_UPDATED_ON DATE,
    D_LAST_UPDATED_BY  NUMBER(19,0),
    BUSINESS_UNIT_INFO VARCHAR2(255 BYTE),
    PROCESSING_STATUS  VARCHAR2(255 BYTE),
    HIDDEN_BY          VARCHAR2(50 BYTE),
    HIDDEN_ON DATE,
    IS_DELETED CHAR(1 BYTE) DEFAULT 'N' NOT NULL ENABLE,
    PRIMARY KEY (ID) ENABLE   
  )
/