--PURPOSE    : PATCH TO ADD NEW TABLES AND INDEXES.
--AUTHOR     : Meghana Ganapaiah
--CREATED ON : 23RD September 2013
ALTER TABLE INBOX_VIEW add CONSTRAINT INBOX_VIEW_USER_FK FOREIGN KEY (CREATED_BY) REFERENCES ORG_USER (ID) ENABLE
/