--PURPOSE    : PATCH TO ADD NEW TABLES AND INDEXES.
--AUTHOR     : Meghana Ganapaiah
--CREATED ON : 23RD September 2013
CREATE TABLE ATTR_VALUE
  (
    ID        NUMBER(19,0) NOT NULL ENABLE,
    VERSION   NUMBER(10,0) NOT NULL ENABLE,
    ATTRIBUTE NUMBER(19,0) NOT NULL ENABLE,
    VALUE     VARCHAR2(4000 BYTE),
    D_CREATED_ON DATE,
    D_INTERNAL_COMMENTS VARCHAR2(255 CHAR),
    D_UPDATED_ON DATE,
    D_LAST_UPDATED_BY NUMBER(19,0),
    D_CREATED_TIME TIMESTAMP (6),
    D_UPDATED_TIME TIMESTAMP (6),
    D_ACTIVE NUMBER(1,0) DEFAULT 1,
    CONSTRAINT ATTR_VALUE_PK PRIMARY KEY (ID)  ENABLE   
  )
/
CREATE INDEX ATTR_VALUE_I2 ON ATTR_VALUE
  (
    ATTRIBUTE
  )
/