--PURPOSE    : PATCH TO ADD TABLE MISCELLANEOUS_EXCEPTIONS
--AUTHOR     : SUSHMA MANTHALE
--CREATED ON : 16-JULY-13

CREATE TABLE MISCELLANEOUS_EXCEPTIONS
  (
    ID                   NUMBER(19,0) NOT NULL ENABLE,
    START_DATE           DATE,
    END_DATE             DATE,
    DEALER               NUMBER(19,0),
    MODIFIER_PERCENTAGE  FLOAT(126),
    CONSTRAINT MISC_EXCPTNS_PK PRIMARY KEY (ID) ENABLE,
    CONSTRAINT MISC_DEALER_FK FOREIGN KEY (DEALER) REFERENCES SERVICE_PROVIDER (ID) ENABLE
  )
/