 --Purpose    : Patch for creating LABOR_PAYMENT_EXCEPTIONS
--Author     : Meghana Ganapaiah
--Created On : 18-SEP-2013
CREATE TABLE LABOR_PAYMENT_EXCEPTIONS
(
    ID NUMBER(19,0) NOT NULL ,
    START_DATE DATE,
    END_DATE DATE,
    DEALER NUMBER(19,0),
    LABOR_HOURS FLOAT(126),
    DESCRIPTION VARCHAR2(255 CHAR),
    CONSTRAINT LABOR_PAYMENT_EXCEPTIONS_PK PRIMARY KEY (ID)
  )
/
