/*Drop all existing synonyms*/
DECLARE
CURSOR ALL_REC IS
SELECT * FROM USER_SYNONYMS;
TYPE TYPE_ALL_REC IS TABLE OF USER_SYNONYMS%ROWTYPE;
T_TYPE_ALL_REC TYPE_ALL_REC;
BEGIN
OPEN ALL_REC;
FETCH ALL_REC BULK COLLECT INTO T_TYPE_ALL_REC;
FOR i in 1..T_TYPE_ALL_REC.count
LOOP
EXECUTE IMMEDIATE 'drop synonym ' || T_TYPE_ALL_REC(I).SYNONYM_NAME;
END LOOP;
close ALL_REC;
END;
/
CREATE OR REPLACE SYNONYM ACTION_DEFINITION FOR NACCO_UAT_TESTING.ACTION_DEFINITION;
CREATE OR REPLACE SYNONYM ACTION_LEVEL FOR NACCO_UAT_TESTING.ACTION_LEVEL;
CREATE OR REPLACE SYNONYM ACTION_NODE FOR NACCO_UAT_TESTING.ACTION_NODE;
CREATE OR REPLACE SYNONYM ADDRESS FOR NACCO_UAT_TESTING.ADDRESS;
CREATE OR REPLACE SYNONYM ADDRESS_BOOK FOR NACCO_UAT_TESTING.ADDRESS_BOOK;
CREATE OR REPLACE SYNONYM ADDRESS_BOOK_ADDRESS_MAPPING FOR NACCO_UAT_TESTING.ADDRESS_BOOK_ADDRESS_MAPPING;
CREATE OR REPLACE SYNONYM ADDRESS_SEQ FOR NACCO_UAT_TESTING.ADDRESS_SEQ;
CREATE OR REPLACE SYNONYM ASSEMBLY FOR NACCO_UAT_TESTING.ASSEMBLY;
CREATE OR REPLACE SYNONYM ASSEMBLY_DEFINITION FOR NACCO_UAT_TESTING.ASSEMBLY_DEFINITION;
CREATE OR REPLACE SYNONYM ASSEMBLY_LEVEL FOR NACCO_UAT_TESTING.ASSEMBLY_LEVEL;
CREATE OR REPLACE SYNONYM BASE_PRICE_VALUE FOR NACCO_UAT_TESTING.BASE_PRICE_VALUE;
CREATE OR REPLACE SYNONYM BRAND FOR NACCO_UAT_TESTING.BRAND;
CREATE OR REPLACE SYNONYM BRAND_ITEM FOR NACCO_UAT_TESTING.BRAND_ITEM;
CREATE OR REPLACE SYNONYM BUSINESS_UNIT FOR NACCO_UAT_TESTING.BUSINESS_UNIT;--  DDL for Synonymn BU_ORG_MAPPING
CREATE OR REPLACE SYNONYM BU_ORG_MAPPING FOR NACCO_UAT_TESTING.BU_ORG_MAPPING;--  DDL for Synonymn BU_USER_MAPPING
CREATE OR REPLACE SYNONYM BU_USER_MAPPING FOR NACCO_UAT_TESTING.BU_USER_MAPPING;--  DDL for Synonymn CLAIM
CREATE OR REPLACE SYNONYM CLAIM FOR NACCO_UAT_TESTING.CLAIM;--  DDL for Synonymn COMPETING_ITEM
CREATE OR REPLACE SYNONYM COMPETING_ITEM FOR NACCO_UAT_TESTING.COMPETING_ITEM;--  DDL for Synonymn COUNTRY
CREATE OR REPLACE SYNONYM COUNTRY FOR NACCO_UAT_TESTING.COUNTRY;--  DDL for Synonymn CRITERIA_EVALUATION_PRECEDENCE
CREATE OR REPLACE SYNONYM CRITERIA_EVALUATION_PRECEDENCE FOR NACCO_UAT_TESTING.CRITERIA_EVALUATION_PRECEDENCE;--  DDL for Synonymn CURRENCT_CONVERSION_FACTOR
CREATE OR REPLACE SYNONYM CURRENCT_CONVERSION_FACTOR FOR NACCO_UAT_TESTING.CURRENCT_CONVERSION_FACTOR;--  DDL for Synonymn CURRENCY_CONVERSION_FACTOR
CREATE OR REPLACE SYNONYM CURRENCY_CONVERSION_FACTOR FOR NACCO_UAT_TESTING.CURRENCY_CONVERSION_FACTOR;--  DDL for Synonymn CURRENCY_EXCHANGE_RATE
CREATE OR REPLACE SYNONYM CURRENCY_EXCHANGE_RATE FOR NACCO_UAT_TESTING.CURRENCY_EXCHANGE_RATE;--  DDL for Synonymn CUSTOMER
CREATE OR REPLACE SYNONYM CUSTOMER FOR NACCO_UAT_TESTING.CUSTOMER;--  DDL for Synonymn DEALERSHIP
CREATE OR REPLACE SYNONYM DEALERSHIP FOR NACCO_UAT_TESTING.DEALERSHIP;--  DDL for Synonymn DEALER_GROUP
CREATE OR REPLACE SYNONYM DEALER_GROUP FOR NACCO_UAT_TESTING.DEALER_GROUP;--  DDL for Synonymn DEALER_SCHEME
CREATE OR REPLACE SYNONYM DEALER_SCHEME FOR NACCO_UAT_TESTING.DEALER_SCHEME;--  DDL for Synonymn DIRECT_CUSTOMER
CREATE OR REPLACE SYNONYM DIRECT_CUSTOMER FOR NACCO_UAT_TESTING.DIRECT_CUSTOMER;--  DDL for Synonymn DIVISION_BU_MAPPING
CREATE OR REPLACE SYNONYM DIVISION_BU_MAPPING FOR NACCO_UAT_TESTING.DIVISION_BU_MAPPING;--  DDL for Synonymn DOCUMENT
CREATE OR REPLACE SYNONYM DOCUMENT FOR NACCO_UAT_TESTING.DOCUMENT;--  DDL for Synonymn DOCUMENT_TYPE
CREATE OR REPLACE SYNONYM DOCUMENT_TYPE FOR NACCO_UAT_TESTING.DOCUMENT_TYPE;--  DDL for Synonymn EVENT_STATE
CREATE OR REPLACE SYNONYM EVENT_STATE FOR NACCO_UAT_TESTING.EVENT_STATE;--  DDL for Synonymn FAILURE_CAUSE
CREATE OR REPLACE SYNONYM FAILURE_CAUSE FOR NACCO_UAT_TESTING.FAILURE_CAUSE;--  DDL for Synonymn FAILURE_CAUSE_DEFINITION
CREATE OR REPLACE SYNONYM FAILURE_CAUSE_DEFINITION FOR NACCO_UAT_TESTING.FAILURE_CAUSE_DEFINITION;--  DDL for Synonymn FAILURE_ROOT_CAUSE
CREATE OR REPLACE SYNONYM FAILURE_ROOT_CAUSE FOR NACCO_UAT_TESTING.FAILURE_ROOT_CAUSE;--  DDL for Synonymn FAILURE_ROOT_CAUSE_DEFINITION
CREATE OR REPLACE SYNONYM FAILURE_ROOT_CAUSE_DEFINITION FOR NACCO_UAT_TESTING.FAILURE_ROOT_CAUSE_DEFINITION;--  DDL for Synonymn FAILURE_STRUCTURE
CREATE OR REPLACE SYNONYM FAILURE_STRUCTURE FOR NACCO_UAT_TESTING.FAILURE_STRUCTURE;--  DDL for Synonymn FAILURE_TYPE
CREATE OR REPLACE SYNONYM FAILURE_TYPE FOR NACCO_UAT_TESTING.FAILURE_TYPE;--  DDL for Synonymn FAILURE_TYPE_DEFINITION
CREATE OR REPLACE SYNONYM FAILURE_TYPE_DEFINITION FOR NACCO_UAT_TESTING.FAILURE_TYPE_DEFINITION;--  DDL for Synonymn FAULT_CODE
CREATE OR REPLACE SYNONYM FAULT_CODE FOR NACCO_UAT_TESTING.FAULT_CODE;--  DDL for Synonymn FAULT_CODE_DEFINITION
CREATE OR REPLACE SYNONYM FAULT_CODE_DEFINITION FOR NACCO_UAT_TESTING.FAULT_CODE_DEFINITION;--  DDL for Synonymn GLOBAL_CONFIGURATION
CREATE OR REPLACE SYNONYM GLOBAL_CONFIGURATION FOR NACCO_UAT_TESTING.GLOBAL_CONFIGURATION;--  DDL for Synonymn I18NACTIONDEFINITION
CREATE OR REPLACE SYNONYM I18NACTIONDEFINITION FOR NACCO_UAT_TESTING.I18NACTIONDEFINITION;--  DDL for Synonymn I18NACTION_DEFINITION
CREATE OR REPLACE SYNONYM I18NACTION_DEFINITION FOR NACCO_UAT_TESTING.I18NACTION_DEFINITION;--  DDL for Synonymn I18NADDITIONALATTRIBUTENAME
CREATE OR REPLACE SYNONYM I18NADDITIONALATTRIBUTENAME FOR NACCO_UAT_TESTING.I18NADDITIONALATTRIBUTENAME;--  DDL for Synonymn I18NADDITIONAL_ATTRIBUTE_NAME
CREATE OR REPLACE SYNONYM I18NADDITIONAL_ATTRIBUTE_NAME FOR NACCO_UAT_TESTING.I18NADDITIONAL_ATTRIBUTE_NAME;--  DDL for Synonymn I18NASSEMBLYDEFINITION
CREATE OR REPLACE SYNONYM I18NASSEMBLYDEFINITION FOR NACCO_UAT_TESTING.I18NASSEMBLYDEFINITION;--  DDL for Synonymn I18NASSEMBLY_DEFINITION
CREATE OR REPLACE SYNONYM I18NASSEMBLY_DEFINITION FOR NACCO_UAT_TESTING.I18NASSEMBLY_DEFINITION;--  DDL for Synonymn I18NCAMPAIGN_TEXT
CREATE OR REPLACE SYNONYM I18NCAMPAIGN_TEXT FOR NACCO_UAT_TESTING.I18NCAMPAIGN_TEXT;--  DDL for Synonymn I18NDOMAIN_RULE_DESCRIPTION
CREATE OR REPLACE SYNONYM I18NDOMAIN_RULE_DESCRIPTION FOR NACCO_UAT_TESTING.I18NDOMAIN_RULE_DESCRIPTION;--  DDL for Synonymn I18NDOMAIN_RULE_TEXT
CREATE OR REPLACE SYNONYM I18NDOMAIN_RULE_TEXT FOR NACCO_UAT_TESTING.I18NDOMAIN_RULE_TEXT;--  DDL for Synonymn I18NFAILURE_CAUSE_DEFINITION
CREATE OR REPLACE SYNONYM I18NFAILURE_CAUSE_DEFINITION FOR NACCO_UAT_TESTING.I18NFAILURE_CAUSE_DEFINITION;--  DDL for Synonymn I18NFAILURE_TYPE_DEFINITION
CREATE OR REPLACE SYNONYM I18NFAILURE_TYPE_DEFINITION FOR NACCO_UAT_TESTING.I18NFAILURE_TYPE_DEFINITION;--  DDL for Synonymn I18NFLR_ROOT_CAUSE_DEFINITION
CREATE OR REPLACE SYNONYM I18NFLR_ROOT_CAUSE_DEFINITION FOR NACCO_UAT_TESTING.I18NFLR_ROOT_CAUSE_DEFINITION;--  DDL for Synonymn I18NITEM_GROUP_TEXT
CREATE OR REPLACE SYNONYM I18NITEM_GROUP_TEXT FOR NACCO_UAT_TESTING.I18NITEM_GROUP_TEXT;--  DDL for Synonymn I18NITEM_TEXT
CREATE OR REPLACE SYNONYM I18NITEM_TEXT FOR NACCO_UAT_TESTING.I18NITEM_TEXT;--  DDL for Synonymn I18NLOV_TEXT
CREATE OR REPLACE SYNONYM I18NLOV_TEXT FOR NACCO_UAT_TESTING.I18NLOV_TEXT;--  DDL for Synonymn I18NMODIFIER_NAME
CREATE OR REPLACE SYNONYM I18NMODIFIER_NAME FOR NACCO_UAT_TESTING.I18NMODIFIER_NAME;--  DDL for Synonymn I18NNON_OEM_PARTS_DESCRIPTION
CREATE OR REPLACE SYNONYM I18NNON_OEM_PARTS_DESCRIPTION FOR NACCO_UAT_TESTING.I18NNON_OEM_PARTS_DESCRIPTION;--  DDL for Synonymn I18NPOLICY_TERMS_CONDITIONS
CREATE OR REPLACE SYNONYM I18NPOLICY_TERMS_CONDITIONS FOR NACCO_UAT_TESTING.I18NPOLICY_TERMS_CONDITIONS;--  DDL for Synonymn I18NTEXT
CREATE OR REPLACE SYNONYM I18NTEXT FOR NACCO_UAT_TESTING.I18NTEXT;--  DDL for Synonymn I18NUPLOAD_ERROR_TEXT
CREATE OR REPLACE SYNONYM I18NUPLOAD_ERROR_TEXT FOR NACCO_UAT_TESTING.I18NUPLOAD_ERROR_TEXT;--  DDL for Synonymn I18N_DOMAIN_RULE_DESCRIPTION
CREATE OR REPLACE SYNONYM I18N_DOMAIN_RULE_DESCRIPTION FOR NACCO_UAT_TESTING.I18N_DOMAIN_RULE_DESCRIPTION;--  DDL for Synonymn I18N_ITEM_TEXT
CREATE OR REPLACE SYNONYM I18N_ITEM_TEXT FOR NACCO_UAT_TESTING.I18N_ITEM_TEXT;--  DDL for Synonymn I18N_MISC_ITEM
CREATE OR REPLACE SYNONYM I18N_MISC_ITEM FOR NACCO_UAT_TESTING.I18N_MISC_ITEM;--  DDL for Synonymn I18N_TEXT
CREATE OR REPLACE SYNONYM I18N_TEXT FOR NACCO_UAT_TESTING.I18N_TEXT;--  DDL for Synonymn INTER_COMPANY
CREATE OR REPLACE SYNONYM INTER_COMPANY FOR NACCO_UAT_TESTING.INTER_COMPANY;--  DDL for Synonymn INVENTORY_ITEM
CREATE OR REPLACE SYNONYM INVENTORY_ITEM FOR NACCO_UAT_TESTING.INVENTORY_ITEM;--  DDL for Synonymn ITEM
CREATE OR REPLACE SYNONYM ITEM FOR NACCO_UAT_TESTING.ITEM;--  DDL for Synonymn ITEMS_IN_GROUP
CREATE OR REPLACE SYNONYM ITEMS_IN_GROUP FOR NACCO_UAT_TESTING.ITEMS_IN_GROUP;--  DDL for Synonymn ITEM_BASE_PRICE
CREATE OR REPLACE SYNONYM ITEM_BASE_PRICE FOR NACCO_UAT_TESTING.ITEM_BASE_PRICE;--  DDL for Synonymn ITEM_COMPOSITION
CREATE OR REPLACE SYNONYM ITEM_COMPOSITION FOR NACCO_UAT_TESTING.ITEM_COMPOSITION;--  DDL for Synonymn ITEM_GROUP
CREATE OR REPLACE SYNONYM ITEM_GROUP FOR NACCO_UAT_TESTING.ITEM_GROUP;--  DDL for Synonymn ITEM_GROUP_LABELS
CREATE OR REPLACE SYNONYM ITEM_GROUP_LABELS FOR NACCO_UAT_TESTING.ITEM_GROUP_LABELS;--  DDL for Synonymn ITEM_SCHEME
CREATE OR REPLACE SYNONYM ITEM_SCHEME FOR NACCO_UAT_TESTING.ITEM_SCHEME;--  DDL for Synonymn ITEM_SCHEME_PURPOSES
CREATE OR REPLACE SYNONYM ITEM_SCHEME_PURPOSES FOR NACCO_UAT_TESTING.ITEM_SCHEME_PURPOSES;--  DDL for Synonymn ITEM_TYPE_MAPPING
CREATE OR REPLACE SYNONYM ITEM_TYPE_MAPPING FOR NACCO_UAT_TESTING.ITEM_TYPE_MAPPING;--  DDL for Synonymn LABEL
CREATE OR REPLACE SYNONYM LABEL FOR NACCO_UAT_TESTING.LABEL;--  DDL for Synonymn LOCALIZED_MESSAGES
CREATE OR REPLACE SYNONYM LOCALIZED_MESSAGES FOR NACCO_UAT_TESTING.LOCALIZED_MESSAGES;--  DDL for Synonymn LOCATION
CREATE OR REPLACE SYNONYM LOCATION FOR NACCO_UAT_TESTING.LOCATION;--  DDL for Synonymn LOGICAL_GROUP
CREATE OR REPLACE SYNONYM LOGICAL_GROUP FOR NACCO_UAT_TESTING.LOGICAL_GROUP;--  DDL for Synonymn LOGIN_HISTORY
CREATE OR REPLACE SYNONYM LOGIN_HISTORY FOR NACCO_UAT_TESTING.LOGIN_HISTORY;--  DDL for Synonymn MARKETING_GROUP
CREATE OR REPLACE SYNONYM MARKETING_GROUP FOR NACCO_UAT_TESTING.MARKETING_GROUP;--  DDL for Synonymn MISC_ITEM
CREATE OR REPLACE SYNONYM MISC_ITEM FOR NACCO_UAT_TESTING.MISC_ITEM;--  DDL for Synonymn MISC_ITEM_CONFIG
CREATE OR REPLACE SYNONYM MISC_ITEM_CONFIG FOR NACCO_UAT_TESTING.MISC_ITEM_CONFIG;--  DDL for Synonymn MISC_ITEM_CRITERIA
CREATE OR REPLACE SYNONYM MISC_ITEM_CRITERIA FOR NACCO_UAT_TESTING.MISC_ITEM_CRITERIA;--  DDL for Synonymn MISC_ITEM_RATE
CREATE OR REPLACE SYNONYM MISC_ITEM_RATE FOR NACCO_UAT_TESTING.MISC_ITEM_RATE;--  DDL for Synonymn MSA
CREATE OR REPLACE SYNONYM MSA FOR NACCO_UAT_TESTING.MSA;--  DDL for Synonymn MST_ADMIN_ACTION
CREATE OR REPLACE SYNONYM MST_ADMIN_ACTION FOR NACCO_UAT_TESTING.MST_ADMIN_ACTION;--  DDL for Synonymn MST_ADMIN_FNC_AREA
CREATE OR REPLACE SYNONYM MST_ADMIN_FNC_AREA FOR NACCO_UAT_TESTING.MST_ADMIN_FNC_AREA;--  DDL for Synonymn MST_ADMIN_FNC_AREA_SEQ
CREATE OR REPLACE SYNONYM MST_ADMIN_FNC_AREA_SEQ FOR NACCO_UAT_TESTING.MST_ADMIN_FNC_AREA_SEQ;--  DDL for Synonymn MST_ADMIN_SUBJECT_AREA
CREATE OR REPLACE SYNONYM MST_ADMIN_SUBJECT_AREA FOR NACCO_UAT_TESTING.MST_ADMIN_SUBJECT_AREA;--  DDL for Synonymn MST_ADMIN_SUBJECT_AREA_SEQ
CREATE OR REPLACE SYNONYM MST_ADMIN_SUBJECT_AREA_SEQ FOR NACCO_UAT_TESTING.MST_ADMIN_SUBJECT_AREA_SEQ;--  DDL for Synonymn NACCO_UAT_TESTING
CREATE OR REPLACE SYNONYM NACCO_UAT_TESTING FOR NACCO_UAT_TESTING.NACCO_UAT_TESTING;--  DDL for Synonymn NATIONAL_ACCOUNT
CREATE OR REPLACE SYNONYM NATIONAL_ACCOUNT FOR NACCO_UAT_TESTING.NATIONAL_ACCOUNT;--  DDL for Synonymn OPTION_INFO
CREATE OR REPLACE SYNONYM OPTION_INFO FOR NACCO_UAT_TESTING.OPTION_INFO;--  DDL for Synonymn ORGANIZATION
CREATE OR REPLACE SYNONYM ORGANIZATION FOR NACCO_UAT_TESTING.ORGANIZATION;--  DDL for Synonymn ORGANIZATION_ADDRESS
CREATE OR REPLACE SYNONYM ORGANIZATION_ADDRESS FOR NACCO_UAT_TESTING.ORGANIZATION_ADDRESS;--  DDL for Synonymn ORG_OWNER_ASSOCIATION
CREATE OR REPLACE SYNONYM ORG_OWNER_ASSOCIATION FOR NACCO_UAT_TESTING.ORG_OWNER_ASSOCIATION;--  DDL for Synonymn ORG_USER
CREATE OR REPLACE SYNONYM ORG_USER FOR NACCO_UAT_TESTING.ORG_USER;--  DDL for Synonymn ORG_USER_BELONGS_TO_ORGS
CREATE OR REPLACE SYNONYM ORG_USER_BELONGS_TO_ORGS FOR NACCO_UAT_TESTING.ORG_USER_BELONGS_TO_ORGS;--  DDL for Synonymn ORIGINAL_EQUIP_MANUFACTURER
CREATE OR REPLACE SYNONYM ORIGINAL_EQUIP_MANUFACTURER FOR NACCO_UAT_TESTING.ORIGINAL_EQUIP_MANUFACTURER;--  DDL for Synonymn PARTY
CREATE OR REPLACE SYNONYM PARTY FOR NACCO_UAT_TESTING.PARTY;--  DDL for Synonymn PARTY_SEQ
CREATE OR REPLACE SYNONYM PARTY_SEQ FOR NACCO_UAT_TESTING.PARTY_SEQ;--  DDL for Synonymn PRODUCT_LOCALE
CREATE OR REPLACE SYNONYM PRODUCT_LOCALE FOR NACCO_UAT_TESTING.PRODUCT_LOCALE;--  DDL for Synonymn PURPOSE
CREATE OR REPLACE SYNONYM PURPOSE FOR NACCO_UAT_TESTING.PURPOSE;--  DDL for Synonymn REPORT_I18N_TEXT
CREATE OR REPLACE SYNONYM REPORT_I18N_TEXT FOR NACCO_UAT_TESTING.REPORT_I18N_TEXT;--  DDL for Synonymn ROLE
CREATE OR REPLACE SYNONYM ROLE FOR NACCO_UAT_TESTING.ROLE;--  DDL for Synonymn ROLE_DEFINITION
CREATE OR REPLACE SYNONYM ROLE_DEFINITION FOR NACCO_UAT_TESTING.ROLE_DEFINITION;--  DDL for Synonymn ROLE_GROUP
CREATE OR REPLACE SYNONYM ROLE_GROUP FOR NACCO_UAT_TESTING.ROLE_GROUP;--  DDL for Synonymn ROLE_PERMISSION_MAPPING
CREATE OR REPLACE SYNONYM ROLE_PERMISSION_MAPPING FOR NACCO_UAT_TESTING.ROLE_PERMISSION_MAPPING;--  DDL for Synonymn ROLE_PERMISSION_MAPPING_SEQ
CREATE OR REPLACE SYNONYM ROLE_PERMISSION_MAPPING_SEQ FOR NACCO_UAT_TESTING.ROLE_PERMISSION_MAPPING_SEQ;--  DDL for Synonymn ROLE_SCHEME
CREATE OR REPLACE SYNONYM ROLE_SCHEME FOR NACCO_UAT_TESTING.ROLE_SCHEME;--  DDL for Synonymn ROLE_SEQ
CREATE OR REPLACE SYNONYM ROLE_SEQ FOR NACCO_UAT_TESTING.ROLE_SEQ;--  DDL for Synonymn SERVICE_PROCEDURE
CREATE OR REPLACE SYNONYM SERVICE_PROCEDURE FOR NACCO_UAT_TESTING.SERVICE_PROCEDURE;--  DDL for Synonymn SERVICE_PROCEDURE_DEFINITION
CREATE OR REPLACE SYNONYM SERVICE_PROCEDURE_DEFINITION FOR NACCO_UAT_TESTING.SERVICE_PROCEDURE_DEFINITION;--  DDL for Synonymn SERVICE_PROVIDER
CREATE OR REPLACE SYNONYM SERVICE_PROVIDER FOR NACCO_UAT_TESTING.SERVICE_PROVIDER;--  DDL for Synonymn SOURCE_SYSTEM_BU_MAPPING
CREATE OR REPLACE SYNONYM SOURCE_SYSTEM_BU_MAPPING FOR NACCO_UAT_TESTING.SOURCE_SYSTEM_BU_MAPPING;--  DDL for Synonymn SOURCE_WAREHOUSE
CREATE OR REPLACE SYNONYM SOURCE_WAREHOUSE FOR NACCO_UAT_TESTING.SOURCE_WAREHOUSE;--  DDL for Synonymn SUBJECT_FUNC_AREA_MAPPING
CREATE OR REPLACE SYNONYM SUBJECT_FUNC_AREA_MAPPING FOR NACCO_UAT_TESTING.SUBJECT_FUNC_AREA_MAPPING;--  DDL for Synonymn SUPERSESSION_ITEM
CREATE OR REPLACE SYNONYM SUPERSESSION_ITEM FOR NACCO_UAT_TESTING.SUPERSESSION_ITEM;--  DDL for Synonymn SUPPLIER
CREATE OR REPLACE SYNONYM SUPPLIER FOR NACCO_UAT_TESTING.SUPPLIER;--  DDL for Synonymn SUPPLIER_LOCATIONS
CREATE OR REPLACE SYNONYM SUPPLIER_LOCATIONS FOR NACCO_UAT_TESTING.SUPPLIER_LOCATIONS;--  DDL for Synonymn TECHNICIAN
CREATE OR REPLACE SYNONYM TECHNICIAN FOR NACCO_UAT_TESTING.TECHNICIAN;--  DDL for Synonymn TEXT
CREATE OR REPLACE SYNONYM TEXT FOR NACCO_UAT_TESTING.TEXT;--  DDL for Synonymn THIRD_PARTY
CREATE OR REPLACE SYNONYM THIRD_PARTY FOR NACCO_UAT_TESTING.THIRD_PARTY;--  DDL for Synonymn TREAD_BUCKET
CREATE OR REPLACE SYNONYM TREAD_BUCKET FOR NACCO_UAT_TESTING.TREAD_BUCKET;--  DDL for Synonymn USER_BU_AVAILABILITY
CREATE OR REPLACE SYNONYM USER_BU_AVAILABILITY FOR NACCO_UAT_TESTING.USER_BU_AVAILABILITY;--  DDL for Synonymn USER_CLUSTER
CREATE OR REPLACE SYNONYM USER_CLUSTER FOR NACCO_UAT_TESTING.USER_CLUSTER;--  DDL for Synonymn USER_GROUP
CREATE OR REPLACE SYNONYM USER_GROUP FOR NACCO_UAT_TESTING.USER_GROUP;--  DDL for Synonymn USER_ROLES
CREATE OR REPLACE SYNONYM USER_ROLES FOR NACCO_UAT_TESTING.USER_ROLES;--  DDL for Synonymn USER_SCHEME
CREATE OR REPLACE SYNONYM USER_SCHEME FOR NACCO_UAT_TESTING.USER_SCHEME;
---For tickets FLEETDM-1 to FLEETDM-69
  
